import { v7 } from "uuid";
import { createProspectingIntent, profileSlotKey } from "./prospecting-schedule";
import type { InterviewPrincipal } from "./interview";

export const PROFILE_READINESS_CATEGORIES = ["fit_target", "disqualifier", "roles", "signals", "geography_language", "rubric", "proof_guardrail", "contact_strategy", "outreach_strategy", "schedule_timezone", "compliance", "output_policy"] as const;
export class ProfileReadinessConflictError extends Error { readonly code = "profile_readiness_conflict"; }
type Workspace = { id: string; companyId: string };
type CandidateInput = { profileId: string; expectedProfileRevision: number; idempotencyKey: string; now?: number; [key: string]: unknown };
type Profile = { id: string; play_id: string; product_id: string; lifecycle: string; revision: number };
type Candidate = { id: string; revision: number; candidate_digest: string; status: string; profile_id: string; configuration_id: string; predecessor_configuration_id: string | null; lifecycle: string; play_id: string; product_id: string; profile_revision: number };

export async function createProfileConfigurationCandidate(database: D1Database, principal: InterviewPrincipal, input: CandidateInput) {
  validateKey(input.idempotencyKey); validateRevision(input.expectedProfileRevision);
  const workspace = await ownedWorkspace(database, principal); const profile = await ownedProfile(database, workspace.id, input.profileId);
  if (profile.revision !== input.expectedProfileRevision) throw new ProfileReadinessConflictError("Stale Profile revision; reload readiness");
  if (["paused", "archived"].includes(profile.lifecycle)) throw new ProfileReadinessConflictError(`Profile is ${profile.lifecycle}`);
  const authority = await resolveAuthority(database, workspace.id, profile);
  const manifest = { schema: "profile-effective-configuration/v1", profile: { id: profile.id, playId: profile.play_id, productId: profile.product_id }, authority, readiness: PROFILE_READINESS_CATEGORIES, policy: { timezone: "America/Toronto", cadence: "weekdays", localTime: "06:00", externalDispatch: false, providerCalls: false, downstreamWrites: false } };
  const manifestJson = stable(manifest); const digest = await sha256(manifestJson); const existing = await database.prepare("SELECT c.id, c.revision, c.candidate_digest FROM profile_configuration_candidates c WHERE c.workspace_id = ? AND c.profile_id = ? AND c.candidate_digest = ? LIMIT 1").bind(workspace.id, profile.id, digest).first<{ id: string; revision: number; candidate_digest: string }>();
  if (existing) return candidateProjection(existing, digest);
  const command = await commandForKey(database, workspace.id, input.idempotencyKey);
  if (command) throw new ProfileReadinessConflictError("Idempotency key was used for another Profile candidate");
  const now = input.now ?? Date.now(); const configurationId = v7(); const candidateId = v7(); const commandId = v7(); const auditId = v7(); const operationDigest = await sha256(stable({ action: "profile.configuration.candidate", profileId: profile.id, revision: profile.revision, digest }));
  const previous = await database.prepare("SELECT id FROM typed_configurations WHERE workspace_id = ? AND owner_type = 'profile' AND owner_id = ? AND kind = 'profile_effective' AND active = 1 LIMIT 1").bind(workspace.id, profile.id).first<{ id: string }>();
  await database.batch([
    database.prepare("INSERT INTO authority_commands (id, workspace_id, created_at, updated_at, revision, command_type, idempotency_key, operation_digest, expected_revision, subject_type, subject_id, status) VALUES (?, ?, ?, ?, 1, 'profile.configuration.candidate', ?, ?, ?, 'profile', ?, 'accepted')").bind(commandId, workspace.id, now, now, input.idempotencyKey, operationDigest, profile.revision, profile.id),
    database.prepare("INSERT INTO typed_configurations (id, workspace_id, created_at, updated_at, revision, company_id, owner_type, owner_id, kind, digest, manifest_json, active) VALUES (?, ?, ?, ?, 1, ?, 'profile', ?, 'profile_effective', ?, ?, 0)").bind(configurationId, workspace.id, now, now, workspace.companyId, profile.id, digest, manifestJson),
    database.prepare("INSERT INTO audit_events (id, workspace_id, actor_type, actor_id, action, subject_type, subject_id, detail_json, created_at) VALUES (?, ?, 'owner', ?, 'profile.configuration.candidate_created', 'profile_configuration_candidate', ?, ?, ?)").bind(auditId, workspace.id, principal.subject, candidateId, stable({ digest, immutable: true }), now),
    database.prepare("INSERT INTO profile_configuration_candidates (id, workspace_id, created_at, updated_at, revision, profile_id, configuration_id, predecessor_configuration_id, authority_command_id, audit_event_id, candidate_digest, status) VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?, 'candidate')").bind(candidateId, workspace.id, now, now, profile.id, configurationId, previous?.id ?? null, commandId, auditId, digest),
  ]);
  return candidateProjection({ id: candidateId, revision: 1, candidate_digest: digest }, digest);
}

export async function activateProfileConfiguration(database: D1Database, principal: InterviewPrincipal, input: { candidateId: string; expectedRevision: number; expectedDigest: string; idempotencyKey: string; now?: number }) {
  validateKey(input.idempotencyKey); validateRevision(input.expectedRevision); if (!validDigest(input.expectedDigest)) throw new ProfileReadinessConflictError("Invalid candidate digest");
  const workspace = await ownedWorkspace(database, principal); const candidate = await database.prepare("SELECT c.*, p.revision AS profile_revision, p.lifecycle, p.play_id, mp.product_id FROM profile_configuration_candidates c JOIN customer_profiles p ON p.id = c.profile_id AND p.workspace_id = c.workspace_id JOIN market_plays mp ON mp.id = p.play_id AND mp.workspace_id = p.workspace_id WHERE c.id = ? AND c.workspace_id = ? LIMIT 1").bind(input.candidateId, workspace.id).first<Candidate>();
  if (!candidate) throw new ProfileReadinessConflictError("Profile configuration candidate is unavailable");
  const prior = await database.prepare("SELECT a.configuration_id, r.id AS run_id, s.id AS schedule_id FROM profile_configuration_activations a JOIN prospecting_runs r ON r.configuration_id = a.configuration_id AND r.trigger_kind = 'initial' JOIN prospecting_schedules s ON s.configuration_id = a.configuration_id AND s.active = 1 WHERE a.candidate_id = ? LIMIT 1").bind(candidate.id).first<{ configuration_id: string; run_id: string; schedule_id: string }>();
  if (prior) return activationProjection(candidate, prior.configuration_id, prior.run_id, prior.schedule_id);
  if (candidate.status !== "candidate" || Number(candidate.revision) !== input.expectedRevision || candidate.candidate_digest !== input.expectedDigest) throw new ProfileReadinessConflictError("Stale Profile configuration candidate; reload readiness");
  if (["paused", "archived"].includes(candidate.lifecycle)) throw new ProfileReadinessConflictError(`Profile is ${candidate.lifecycle}`);
  await resolveAuthority(database, workspace.id, { id: candidate.profile_id, play_id: candidate.play_id, product_id: candidate.product_id, lifecycle: candidate.lifecycle, revision: Number(candidate.profile_revision) });
  const command = await commandForKey(database, workspace.id, input.idempotencyKey); if (command) throw new ProfileReadinessConflictError("Idempotency key was used for another Profile activation");
  const now = input.now ?? Date.now(); const activationId = v7(); const commandId = v7(); const auditId = v7(); const scheduleId = v7(); const operationDigest = await sha256(stable({ action: "profile.configuration.activate", candidateId: candidate.id, digest: candidate.candidate_digest }));
  const scheduleKey = profileSlotKey(candidate.profile_id, localDate(now), "06:00", torontoOffset(now));
  await database.batch([
    database.prepare("INSERT INTO authority_commands (id, workspace_id, created_at, updated_at, revision, command_type, idempotency_key, operation_digest, expected_revision, subject_type, subject_id, status) VALUES (?, ?, ?, ?, 1, 'profile.configuration.activate', ?, ?, ?, 'profile_configuration_candidate', ?, 'accepted')").bind(commandId, workspace.id, now, now, input.idempotencyKey, operationDigest, input.expectedRevision, candidate.id),
    database.prepare("UPDATE typed_configurations SET active = 0, updated_at = ?, revision = revision + 1 WHERE workspace_id = ? AND owner_type = 'profile' AND owner_id = ? AND kind = 'profile_effective' AND active = 1").bind(now, workspace.id, candidate.profile_id),
    database.prepare("UPDATE typed_configurations SET active = 1, updated_at = ?, revision = revision + 1 WHERE id = ? AND workspace_id = ? AND active = 0").bind(now, candidate.configuration_id, workspace.id),
    database.prepare("INSERT INTO audit_events (id, workspace_id, actor_type, actor_id, action, subject_type, subject_id, detail_json, created_at) VALUES (?, ?, 'owner', ?, 'profile.configuration.activated', 'profile_configuration_activation', ?, ?, ?)").bind(auditId, workspace.id, principal.subject, activationId, stable({ candidateId: candidate.id, digest: candidate.candidate_digest }), now),
    database.prepare("INSERT INTO profile_configuration_activations (id, workspace_id, profile_id, candidate_id, previous_configuration_id, configuration_id, authority_command_id, audit_event_id, operation_digest, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(activationId, workspace.id, candidate.profile_id, candidate.id, candidate.predecessor_configuration_id, candidate.configuration_id, commandId, auditId, operationDigest, now),
    database.prepare("UPDATE profile_configuration_candidates SET status = 'activated', updated_at = ?, revision = revision + 1 WHERE id = ? AND workspace_id = ? AND status = 'candidate'").bind(now, candidate.id, workspace.id),
    database.prepare("INSERT INTO prospecting_schedules (id, workspace_id, created_at, updated_at, revision, profile_id, configuration_id, configuration_digest, schedule_key, timezone, intended_local_time, utc_offset_minutes, cadence, next_run_at, last_successful_watermark, active, execution_state, authority_command_id, operation_digest, idempotency_key) VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?, 'America/Toronto', '06:00', ?, 'weekdays', ?, NULL, 1, 'blocked_missing_capability', ?, ?, ?)").bind(scheduleId, workspace.id, now, now, candidate.profile_id, candidate.configuration_id, candidate.candidate_digest, scheduleKey, torontoOffset(now), nextTorontoWeekday0600(now), commandId, await sha256(`${operationDigest}:schedule`), `${input.idempotencyKey}-schedule`),
  ]);
  const initialRun = await createProspectingIntent(database, workspace.id, { profileId: candidate.profile_id, configurationId: candidate.configuration_id, configurationDigest: candidate.candidate_digest, scheduleId, triggerKind: "initial", triggerKey: `initial:profile:${candidate.profile_id}:${candidate.configuration_id}`, idempotencyKey: `${input.idempotencyKey}-initial`, at: now, watermark: null, manifest: { configuration: candidate.candidate_digest } });
  return activationProjection(candidate, candidate.configuration_id, initialRun.id, scheduleId);
}

async function resolveAuthority(database: D1Database, workspaceId: string, profile: Profile) {
  const product = await database.prepare("SELECT id, digest FROM typed_configurations WHERE workspace_id = ? AND owner_type = 'product' AND owner_id = ? AND kind = 'product_discovery' AND active = 1 LIMIT 1").bind(workspaceId, profile.product_id).first<{ id: string; digest: string }>();
  if (!product || !validDigest(product.digest)) throw new ProfileReadinessConflictError("Product Discovery Configuration authority is unavailable");
  if (profile.lifecycle !== "draft" && profile.lifecycle !== "ready") throw new ProfileReadinessConflictError("Profile lifecycle is not eligible");
  return { productConfiguration: { id: product.id, digest: product.digest }, acceptedPlay: { id: profile.play_id }, offer: { profileId: profile.id, status: "awaiting-Phase-3-offer-authority" }, sourcePolicy: "inherited_product_configuration", runnerPolicy: "inherited_product_configuration", scheduleSemantics: { timezone: "America/Toronto", dst: "offset-keyed", misfire: "once-within-24h-otherwise-skip" }, replacementDirectives: "immutable-replacement-required" };
}
async function ownedWorkspace(database: D1Database, principal: InterviewPrincipal): Promise<Workspace> { const legacy = principal.legacySubject ?? principal.subject; const row = await database.prepare("SELECT w.id, c.id AS company_id FROM workspaces w JOIN companies c ON c.workspace_id = w.id WHERE w.owner_subject IN (?, ?) ORDER BY CASE w.owner_subject WHEN ? THEN 0 ELSE 1 END LIMIT 1").bind(principal.subject, legacy, principal.subject).first<{ id: string; company_id: string }>(); if (!row) throw new ProfileReadinessConflictError("Commercial workspace authority is unavailable"); return { id: row.id, companyId: row.company_id }; }
async function ownedProfile(database: D1Database, workspaceId: string, id: string): Promise<Profile> { const row = await database.prepare("SELECT cp.id, cp.play_id, cp.lifecycle, cp.revision, mp.product_id FROM customer_profiles cp JOIN market_plays mp ON mp.id = cp.play_id AND mp.workspace_id = cp.workspace_id WHERE cp.id = ? AND cp.workspace_id = ? LIMIT 1").bind(id, workspaceId).first<Profile>(); if (!row) throw new ProfileReadinessConflictError("Profile authority is unavailable"); return { ...row, revision: Number(row.revision) }; }
async function commandForKey(database: D1Database, workspaceId: string, key: string) { return database.prepare("SELECT id FROM authority_commands WHERE workspace_id = ? AND idempotency_key = ? LIMIT 1").bind(workspaceId, key).first(); }
function candidateProjection(row: { id: string; revision: number; candidate_digest: string }, digest: string) { return { id: row.id, revision: Number(row.revision), digest, status: "candidate_not_active" as const, immutable: true }; }
function activationProjection(candidate: Candidate, configurationId: string, runId: string | null, scheduleId: string) { return { configuration: { id: configurationId, digest: candidate.candidate_digest, active: true, immutable: true }, initialRun: { id: runId, trigger: "initial", executionState: "blocked_missing_capability" }, schedule: { id: scheduleId, timezone: "America/Toronto", cadence: "weekdays", executionState: "blocked_missing_capability" } }; }
function localDate(at: number) { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Toronto", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(at)); }
function torontoOffset(at: number) { const parts = new Intl.DateTimeFormat("en-US", { timeZone: "America/Toronto", timeZoneName: "longOffset" }).formatToParts(new Date(at)); const value = parts.find((part) => part.type === "timeZoneName")?.value ?? "GMT-05:00"; const match = /GMT([+-])(\d{2}):(\d{2})/.exec(value); return match ? (match[1] === "+" ? 1 : -1) * (Number(match[2]) * 60 + Number(match[3])) : -300; }
function nextTorontoWeekday0600(now: number) { let instant = now + 60_000; for (let i = 0; i < 8 * 24 * 60; i++) { const d = new Date(instant); const local = new Intl.DateTimeFormat("en-US", { timeZone: "America/Toronto", weekday: "short", hour: "2-digit", hourCycle: "h23", minute: "2-digit" }).formatToParts(d); const value = (t: string) => local.find((p) => p.type === t)?.value; if (!["Sat", "Sun"].includes(value("weekday") ?? "") && value("hour") === "06" && value("minute") === "00") return instant; instant += 60_000; } throw new ProfileReadinessConflictError("Unable to resolve Toronto schedule intent"); }
function validateKey(value: string) { if (!/^[a-f0-9-]{20,100}$/i.test(value)) throw new ProfileReadinessConflictError("Invalid idempotency key"); }
function validateRevision(value: number) { if (!Number.isInteger(value) || value < 1) throw new ProfileReadinessConflictError("Invalid expected revision"); }
function validDigest(value: unknown): value is string { return typeof value === "string" && /^[a-f0-9]{64}$/.test(value); }
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") { const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stable(record[key])}`).join(",")}}`; } return JSON.stringify(value); }
async function sha256(value: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
