import { consumeCsrfToken, csrfTokenFromRequest, CsrfTokenError, issueCsrfToken, withCsrfCookie } from "./csrf";
import { admitPilotOwner, PilotAccessError } from "./pilot-access";
import { readBoundedJson, validateSameOriginMutation } from "./request-security";
import { activateProfileConfiguration, createProfileConfigurationCandidate, readProfileReadiness, ProfileReadinessConflictError } from "./profile-readiness";
import { createManualProspectingIntent, ProspectingScheduleConflictError } from "./prospecting-schedule";
import { decideQualifiedProspect, readProspectingProjection, ProspectReviewError } from "./prospect-review";
import { revokeRunnerAssignment, submitRunnerObservations, RunnerAssignmentError } from "./runner-assignment";

export const PROSPECTING_MUTATION_INTENT="prospecting-mutation"; export const MAX_PROSPECTING_BODY_BYTES=8192;
export type ProspectingHandlerDependencies={database:D1Database;subjectPepper:string;pilotOwnerEmail:string;getIdentity():Promise<{email:string;displayName:string}|null>; runnerCapabilitySecret?:Uint8Array; runnerIngressEnabled?:boolean};
type Principal={subject:string;legacySubject?:string;displayName?:string};

export async function handleProspectingGet(request:Request,d:ProspectingHandlerDependencies){try{const principal=await owner(d);const requested=optionalId(new URL(request.url).searchParams.get("profileId"));const projection=await readProspectingProjection(d.database,principal);const profileId=requested??(projection.profiles[0] as {id?:string}|undefined)?.id??null;if(profileId)projection.readiness=await readProfileReadiness(d.database,principal,profileId);return csrf(await projected(d.database,principal,projection));}catch(error){return denial(error);}}
export async function handleProspectingPost(request:Request,d:ProspectingHandlerDependencies){try{const principal=await owner(d);const rejected=validateSameOriginMutation(request,PROSPECTING_MUTATION_INTENT,MAX_PROSPECTING_BODY_BYTES);if(rejected)return json({error:rejected.error},rejected.status);await consumeCsrfToken(d.database,principal.subject,csrfTokenFromRequest(request));const body=await readBoundedJson(request,MAX_PROSPECTING_BODY_BYTES);if(!record(body)||typeof body.action!=="string"||!ACTIONS.includes(body.action as Action))return json({error:"unsupported_action"},400);assertClosed(body,body.action as Action);const profileId=await dispatch(body.action as Action,body,d.database,principal);const projection=await readProspectingProjection(d.database,principal);if(profileId)projection.readiness=await readProfileReadiness(d.database,principal,profileId);return csrf(await projected(d.database,principal,projection));}catch(error){if(error instanceof CsrfTokenError)return json({error:error.code},403);if(conflict(error))return json({error:"command_conflict"},409);if(error instanceof SyntaxError)return json({error:"invalid_json"},400);if(error instanceof Error&&"status" in error&&(error as {status:number}).status===413)return json({error:"payload_too_large"},413);return denial(error);}}

/** This is deliberately not a browser route: capability verification is the only authority. */
export async function handleRunnerIngress(request:Request,d?:Pick<ProspectingHandlerDependencies,"database"|"runnerCapabilitySecret"|"runnerIngressEnabled">){if(!d?.runnerIngressEnabled||!d.runnerCapabilitySecret)return json({error:"runner_ingress_unavailable"},404);try{if(request.headers.get("content-type")?.toLowerCase().startsWith("application/json")!==true)return json({error:"runner_ingress_unavailable"},404);const body=await readBoundedJson(request,MAX_PROSPECTING_BODY_BYTES);if(!record(body)||Object.keys(body).some(k=>!["capability","idempotencyKey","payload","status"].includes(k))||typeof body.capability!=="string"||typeof body.idempotencyKey!=="string"||!record(body.payload))return json({error:"runner_ingress_unavailable"},404);const result=await submitRunnerObservations(d.database,{capability:body.capability,idempotencyKey:body.idempotencyKey,capabilitySecret:d.runnerCapabilitySecret,payload:body.payload,status:body.status==="partial"?"partial":"complete",now:Date.now()});return json({submissionId:result.submissionId,replayed:result.replayed});}catch{return json({error:"runner_ingress_unavailable"},404);}}

const ACTIONS=["read_profile_readiness","create_candidate","activate","manual_find","issue_assignment","revoke_assignment","review"] as const; type Action=typeof ACTIONS[number];
async function dispatch(action:Action,body:Record<string,unknown>,database:D1Database,principal:Principal):Promise<string|null>{
 if(action==="read_profile_readiness")return requiredId(body,"profileId");
 if(action==="create_candidate"){const profileId=requiredId(body,"profileId");await createProfileConfigurationCandidate(database,principal,{profileId,expectedProfileRevision:revision(body,"expectedRevision"),idempotencyKey:key(body)});return profileId;}
 if(action==="activate"){await activateProfileConfiguration(database,principal,{candidateId:requiredId(body,"candidateId"),expectedRevision:revision(body,"expectedRevision"),expectedDigest:digest(body,"expectedDigest"),idempotencyKey:key(body)});return null;}
 if(action==="manual_find"){const profileId=requiredId(body,"profileId"),configuration=await database.prepare("SELECT id,digest FROM typed_configurations WHERE workspace_id=(SELECT id FROM workspaces WHERE owner_subject IN (?,?) ORDER BY CASE owner_subject WHEN ? THEN 0 ELSE 1 END LIMIT 1) AND owner_type='profile' AND owner_id=? AND kind='profile_effective' AND active=1 LIMIT 1").bind(principal.subject,principal.legacySubject??principal.subject,principal.subject,profileId).first<{id:string;digest:string}>();if(!configuration)throw new ProspectingScheduleConflictError("Active Profile configuration is unavailable");await createManualProspectingIntent(database,(await workspaceId(database,principal)),{profileId,configurationId:configuration.id,configurationDigest:configuration.digest,idempotencyKey:key(body),at:Date.now()});return profileId;}
 if(action==="issue_assignment")throw new RunnerAssignmentError("Runner capability is unavailable");
 if(action==="revoke_assignment"){await revokeRunnerAssignment(database,{workspaceId:await workspaceId(database,principal),assignmentId:requiredId(body,"assignmentId"),reason:requiredText(body,"reason",2000),idempotencyKey:key(body),now:Date.now()});return null;}
 await decideQualifiedProspect(database,principal,{prospectId:requiredId(body,"prospectId"),assessmentId:requiredId(body,"assessmentId"),decision:enumValue(body,"decision",["approve","reject","defer"]),reason:requiredText(body,"reason",2000),...(body.reviewAt===undefined?{}:{reviewAt:timestamp(body,"reviewAt")}),expectedRevision:revision(body,"expectedRevision"),idempotencyKey:key(body)});return null;
}
function assertClosed(body:Record<string,unknown>,action:Action){const fields:Record<Action,readonly string[]>={read_profile_readiness:["action","profileId"],create_candidate:["action","profileId","expectedRevision","idempotencyKey"],activate:["action","candidateId","expectedRevision","expectedDigest","idempotencyKey"],manual_find:["action","profileId","idempotencyKey"],issue_assignment:["action","runId","profileId","configurationId","configurationDigest","toolConfigurationDigest","expiresAt","idempotencyKey"],revoke_assignment:["action","assignmentId","reason","idempotencyKey"],review:["action","prospectId","assessmentId","decision","reason","reviewAt","expectedRevision","idempotencyKey"]};if(Object.keys(body).some(k=>!fields[action].includes(k)))throw new ProspectReviewError("Invalid command");}
async function projected(database:D1Database,principal:Principal,value:unknown){return Response.json(value,{headers:headers()});}async function csrf(database:D1Database,principal:Principal,response:Response){return withCsrfCookie(response,await issueCsrfToken(database,principal.subject));}
async function owner(d:ProspectingHandlerDependencies){return admitPilotOwner(await d.getIdentity(),d.pilotOwnerEmail,d.subjectPepper);} async function workspaceId(database:D1Database,p:Principal){const w=await database.prepare("SELECT id FROM workspaces WHERE owner_subject IN (?,?) ORDER BY CASE owner_subject WHEN ? THEN 0 ELSE 1 END LIMIT 1").bind(p.subject,p.legacySubject??p.subject,p.subject).first<{id:string}>();if(!w)throw new PilotAccessError();return w.id;}
function json(value:unknown,status=200){return Response.json(value,{status,headers:headers()});} function headers(){return{"cache-control":"no-store","x-content-type-options":"nosniff"};} function denial(error:unknown){return error instanceof PilotAccessError?json({error:"private_workspace_unavailable"},404):json({error:"server_error"},500);}function conflict(e:unknown){return e instanceof ProspectReviewError||e instanceof ProfileReadinessConflictError||e instanceof ProspectingScheduleConflictError||e instanceof RunnerAssignmentError;}
function record(x:unknown):x is Record<string,unknown>{return!!x&&typeof x==="object"&&!Array.isArray(x);}function optionalId(x:string|null){if(x===null)return null;if(!x.trim()||x.length>160)throw new PilotAccessError();return x.trim();}function requiredId(b:Record<string,unknown>,k:string){return requiredText(b,k,160);}function requiredText(b:Record<string,unknown>,k:string,n:number){const x=b[k];if(typeof x!=="string"||!x.normalize("NFC").trim()||x.length>n)throw new ProspectReviewError("Invalid command");return x.normalize("NFC").trim();}function key(b:Record<string,unknown>){return requiredText(b,"idempotencyKey",160);}function revision(b:Record<string,unknown>,k:string){const x=b[k];if(!Number.isSafeInteger(x)||(x as number)<1)throw new ProspectReviewError("Invalid command");return x as number;}function timestamp(b:Record<string,unknown>,k:string){const x=b[k];if(!Number.isSafeInteger(x)||(x as number)<=0)throw new ProspectReviewError("Invalid command");return x as number;}function digest(b:Record<string,unknown>,k:string){const x=requiredText(b,k,64).toLowerCase();if(!/^[a-f0-9]{64}$/.test(x))throw new ProspectReviewError("Invalid command");return x;}function enumValue<T extends readonly string[]>(b:Record<string,unknown>,k:string,v:T):T[number]{const x=b[k];if(typeof x!=="string"||!v.includes(x))throw new ProspectReviewError("Invalid command");return x as T[number];}
