import { v7 } from "uuid";
import type { RunnerAssignmentEnvelope, RunnerPort } from "./ports/runner";

export class RunnerAssignmentError extends Error { readonly code = "runner_assignment_rejected"; }
type Quotas = { maxBytes: number; maxFindings: number; maxSources: number };
type Ledger = { quotas: Quotas; provider: string; model: string; instructionVersion: string; toolConfigurationDigest: string; allowedTools: string[]; grantReference: string };
type IssueInput = { workspaceId:string; runId:string; profileId:string; configurationId:string; configurationDigest:string; audience:string; expiresAt:number; instructionVersion:string; toolConfigurationDigest:string; quotas:Quotas; grantReference:string; reason:string; idempotencyKey:string; now:number; capabilitySecret:Uint8Array; provider?:string; model?:string; allowedTools?:readonly string[] };
type SubmitInput = { capability:string; idempotencyKey:string; payload:unknown; now:number; capabilitySecret:Uint8Array; audience?:string };
type Capability = { assignmentId:string; workspaceId:string; runId:string; profileId:string; configurationId:string; configurationDigest:string; audience:string; nonce:string; expiresAt:number; scope:"runner.observations.append/v1" };

/** Issues a signed, one-purpose capability.  The database retains hashes and immutable ledger metadata only. */
export async function issueRunnerAssignment(database:D1Database,input:IssueInput) {
  validateIssue(input);
  const run=await database.prepare("SELECT r.id,r.execution_state,r.configuration_id,r.configuration_digest FROM prospecting_runs r JOIN typed_configurations c ON c.id=r.configuration_id AND c.workspace_id=r.workspace_id AND c.owner_type='profile' AND c.owner_id=r.profile_id AND c.kind='profile_effective' AND c.active=1 WHERE r.id=? AND r.workspace_id=? AND r.profile_id=? LIMIT 1").bind(input.runId,input.workspaceId,input.profileId).first<{id:string;execution_state:string;configuration_id:string;configuration_digest:string}>();
  if(!run||!["queued","assigned","running"].includes(run.execution_state)||run.configuration_id!==input.configurationId||run.configuration_digest!==input.configurationDigest) throw reject();
  const ledger:Ledger={quotas:input.quotas,provider:bounded(input.provider??"runner-provider",256),model:bounded(input.model??"runner-model",256),instructionVersion:input.instructionVersion,toolConfigurationDigest:input.toolConfigurationDigest,allowedTools:normalizeTools(input.allowedTools??[]),grantReference:bounded(input.grantReference,256)};
  const ledgerJson=canonical(ledger), quotaDigest=await sha256(ledgerJson);
  const existing=await database.prepare("SELECT a.id,c.operation_digest FROM runner_assignments a JOIN authority_commands c ON c.id=a.authority_command_id WHERE a.workspace_id=? AND c.idempotency_key=? LIMIT 1").bind(input.workspaceId,input.idempotencyKey).first<{id:string;operation_digest:string}>();
  // Generate deterministic operation material before checking an idempotency replay.
  const operationShape={action:"runner.assignment.issue",runId:input.runId,profileId:input.profileId,configurationId:input.configurationId,configurationDigest:input.configurationDigest,audience:input.audience,expiresAt:input.expiresAt,ledgerDigest:quotaDigest,reason:bounded(input.reason,256)};
  const operationDigest=await sha256(canonical(operationShape));
  if(existing){if(existing.operation_digest!==operationDigest)throw reject();return{assignmentId:existing.id,capability:null,replayed:true};}
  const assignmentId=v7(),nonce=randomToken(); const payload:Capability={assignmentId,workspaceId:input.workspaceId,runId:input.runId,profileId:input.profileId,configurationId:input.configurationId,configurationDigest:input.configurationDigest,audience:input.audience,nonce,expiresAt:input.expiresAt,scope:"runner.observations.append/v1"};
  const capability=await signCapability(payload,input.capabilitySecret),tokenHash=await sha256(capability),nonceHash=await sha256(nonce),commandId=v7(),auditId=v7();
  try { await database.batch([
    database.prepare("INSERT INTO authority_commands (id,workspace_id,created_at,updated_at,revision,command_type,idempotency_key,operation_digest,expected_revision,subject_type,subject_id,status) VALUES (?,?,?,?,1,'runner.assignment.issue',?,?,1,'prospecting_run',?,'accepted')").bind(commandId,input.workspaceId,input.now,input.now,input.idempotencyKey,operationDigest,input.runId),
    database.prepare("INSERT INTO audit_events (id,workspace_id,actor_type,actor_id,action,subject_type,subject_id,detail_json,created_at) VALUES (?,?,'system','runner-assignment-service','runner.assignment.issued','runner_assignment',?,?,?)").bind(auditId,input.workspaceId,assignmentId,canonical({operationDigest,reason:operationShape.reason,ledger,tokenStored:"hash_only"}),input.now),
    database.prepare("INSERT INTO runner_assignments (id,workspace_id,created_at,updated_at,revision,run_id,profile_id,configuration_id,configuration_digest,audience,token_hash,nonce_hash,instruction_version,tool_configuration_digest,quota_json,quota_digest,expires_at,status,authority_command_id,audit_event_id) VALUES (?,?,?,?,1,?,?,?,?,?,?,?,?,?,?,?,?, 'issued',?,?)").bind(assignmentId,input.workspaceId,input.now,input.now,input.runId,input.profileId,input.configurationId,input.configurationDigest,input.audience,tokenHash,nonceHash,ledger.instructionVersion,ledger.toolConfigurationDigest,ledgerJson,quotaDigest,input.expiresAt,commandId,auditId),
    database.prepare("UPDATE prospecting_runs SET execution_state=CASE WHEN execution_state='queued' THEN 'assigned' ELSE execution_state END,updated_at=?,revision=revision+1 WHERE id=? AND workspace_id=? AND execution_state IN ('queued','assigned','running')").bind(input.now,input.runId,input.workspaceId),
  ]); } catch { const winner=await database.prepare("SELECT a.id,c.operation_digest FROM runner_assignments a JOIN authority_commands c ON c.id=a.authority_command_id WHERE a.workspace_id=? AND c.idempotency_key=? LIMIT 1").bind(input.workspaceId,input.idempotencyKey).first<{id:string;operation_digest:string}>(); if(winner&&winner.operation_digest===operationDigest)return{assignmentId:winner.id,capability:null,replayed:true}; throw reject(); }
  return{assignmentId,capability,replayed:false};
}

export async function revokeRunnerAssignment(database:D1Database,input:{workspaceId:string;assignmentId:string;reason:string;idempotencyKey:string;now:number}) {
  if(!input.workspaceId||!input.assignmentId||!input.idempotencyKey)throw reject(); const reason=bounded(input.reason,256); const operationDigest=await sha256(canonical({action:"runner.assignment.revoke",assignmentId:input.assignmentId,reason}));
  const prior=await database.prepare("SELECT r.assignment_id,c.operation_digest FROM runner_assignment_revocations r JOIN authority_commands c ON c.id=r.authority_command_id WHERE r.workspace_id=? AND c.idempotency_key=? LIMIT 1").bind(input.workspaceId,input.idempotencyKey).first<{assignment_id:string;operation_digest:string}>();
  if(prior){if(prior.assignment_id!==input.assignmentId||prior.operation_digest!==operationDigest)throw reject();return{replayed:true};}
  const commandId=v7(),auditId=v7(),revocationId=v7();
  try { const result=await database.batch([
    database.prepare("INSERT INTO authority_commands (id,workspace_id,created_at,updated_at,revision,command_type,idempotency_key,operation_digest,expected_revision,subject_type,subject_id,status) SELECT ?,?,?,?,1,'runner.assignment.revoke',?,?,1,'runner_assignment',?,'accepted' WHERE EXISTS (SELECT 1 FROM runner_assignments WHERE id=? AND workspace_id=? AND status='issued')").bind(commandId,input.workspaceId,input.now,input.now,input.idempotencyKey,operationDigest,input.assignmentId,input.assignmentId,input.workspaceId),
    database.prepare("INSERT INTO audit_events (id,workspace_id,actor_type,actor_id,action,subject_type,subject_id,detail_json,created_at) SELECT ?,?,'system','runner-assignment-service','runner.assignment.revoked','runner_assignment',?,?,? WHERE EXISTS (SELECT 1 FROM authority_commands WHERE id=? AND workspace_id=?)").bind(auditId,input.workspaceId,input.assignmentId,canonical({operationDigest,reason}),input.now,commandId,input.workspaceId),
    database.prepare("INSERT INTO runner_assignment_revocations (id,workspace_id,assignment_id,reason,authority_command_id,audit_event_id,operation_digest,created_at) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM authority_commands WHERE id=? AND workspace_id=?)").bind(revocationId,input.workspaceId,input.assignmentId,reason,commandId,auditId,operationDigest,input.now,commandId,input.workspaceId),
    database.prepare("UPDATE runner_assignments SET status='revoked',updated_at=?,revision=revision+1 WHERE id=? AND workspace_id=? AND status='issued' AND EXISTS (SELECT 1 FROM runner_assignment_revocations WHERE assignment_id=?)").bind(input.now,input.assignmentId,input.workspaceId,input.assignmentId),
  ]); if(!result[0]?.meta?.changes)throw reject(); } catch { const winner=await database.prepare("SELECT r.assignment_id,c.operation_digest FROM runner_assignment_revocations r JOIN authority_commands c ON c.id=r.authority_command_id WHERE r.workspace_id=? AND c.idempotency_key=? LIMIT 1").bind(input.workspaceId,input.idempotencyKey).first<{assignment_id:string;operation_digest:string}>();if(winner&&winner.assignment_id===input.assignmentId&&winner.operation_digest===operationDigest)return{replayed:true};throw reject(); }
  return{replayed:false};
}

/** Atomically appends a bounded proposal.  Qualification, state changes, transports and credentials are absent by design. */
export async function submitRunnerObservations(database:D1Database,input:SubmitInput) {
  const capability=await verifyCapability(input.capability,input.capabilitySecret); if(capability.scope!=="runner.observations.append/v1"||capability.expiresAt<=input.now||input.audience!==undefined&&input.audience!==capability.audience)throw reject();
  const assignment=await database.prepare("SELECT a.id,a.workspace_id,a.run_id,a.configuration_id,a.configuration_digest,a.audience,a.token_hash,a.nonce_hash,a.quota_json,a.expires_at,a.status FROM runner_assignments a JOIN prospecting_runs r ON r.id=a.run_id AND r.workspace_id=a.workspace_id WHERE a.id=? AND a.workspace_id=? AND a.run_id=? AND a.profile_id=? AND a.configuration_id=? AND a.configuration_digest=? AND r.execution_state IN ('assigned','running') LIMIT 1").bind(capability.assignmentId,capability.workspaceId,capability.runId,capability.profileId,capability.configurationId,capability.configurationDigest).first<{id:string;workspace_id:string;run_id:string;configuration_id:string;configuration_digest:string;audience:string;token_hash:string;nonce_hash:string;quota_json:string;expires_at:number;status:string}>();
  if(!assignment||assignment.status!=="issued"||assignment.expires_at<=input.now||assignment.audience!==capability.audience||assignment.token_hash!==await sha256(input.capability)||assignment.nonce_hash!==await sha256(capability.nonce))throw reject();
  const ledger=parseLedger(assignment.quota_json),normalized=normalizeSubmission(input.payload,ledger); const submissionJson=canonical(normalized),submissionDigest=await sha256(submissionJson),provenanceJson=canonical(normalized.provenance),provenanceDigest=await sha256(provenanceJson),operationDigest=await sha256(canonical({action:"runner.submission",assignmentId:assignment.id,submissionDigest,idempotencyKey:input.idempotencyKey}));
  const existing=await database.prepare("SELECT id,operation_digest FROM runner_submissions WHERE workspace_id=? AND idempotency_key=? LIMIT 1").bind(assignment.workspace_id,input.idempotencyKey).first<{id:string;operation_digest:string}>(); if(existing){if(existing.operation_digest!==operationDigest)throw reject();return{submissionId:existing.id,replayed:true};}
  const submissionId=v7(),bytes=new TextEncoder().encode(submissionJson).byteLength,findings=normalized.findings.length,sources=normalized.sources.length;
  try { const inserted=await database.prepare("INSERT INTO runner_submissions (id,workspace_id,run_id,assignment_id,configuration_id,submission_json,submission_digest,provenance_json,provenance_digest,status,operation_digest,idempotency_key,created_at) SELECT ?,?,?,?,?,?,?,?,?,'received',?,?,? WHERE EXISTS (SELECT 1 FROM runner_assignments a JOIN prospecting_runs r ON r.id=a.run_id AND r.workspace_id=a.workspace_id WHERE a.id=? AND a.workspace_id=? AND a.run_id=? AND a.configuration_id=? AND a.configuration_digest=? AND a.audience=? AND a.status='issued' AND a.expires_at>?) AND ? >= 0 AND ? >= 0 AND ? >= 0 AND COALESCE((SELECT SUM(length(submission_json)) FROM runner_submissions WHERE assignment_id=?),0)+?<=? AND COALESCE((SELECT SUM(json_array_length(submission_json,'$.findings')) FROM runner_submissions WHERE assignment_id=?),0)+?<=? AND COALESCE((SELECT SUM(json_array_length(submission_json,'$.sources')) FROM runner_submissions WHERE assignment_id=?),0)+?<=?").bind(submissionId,assignment.workspace_id,assignment.run_id,assignment.id,assignment.configuration_id,submissionJson,submissionDigest,provenanceJson,provenanceDigest,operationDigest,input.idempotencyKey,input.now,assignment.id,assignment.workspace_id,assignment.run_id,assignment.configuration_id,assignment.configuration_digest,assignment.audience,input.now,bytes,findings,sources,assignment.id,bytes,ledger.quotas.maxBytes,assignment.id,findings,ledger.quotas.maxFindings,assignment.id,sources,ledger.quotas.maxSources).run(); if(!inserted.meta.changes)throw reject(); } catch { const winner=await database.prepare("SELECT id,operation_digest FROM runner_submissions WHERE workspace_id=? AND idempotency_key=? LIMIT 1").bind(assignment.workspace_id,input.idempotencyKey).first<{id:string;operation_digest:string}>();if(winner&&winner.operation_digest===operationDigest)return{submissionId:winner.id,replayed:true};throw reject(); }
  return{submissionId,replayed:false};
}

export async function deliverRunnerAssignment(port:RunnerPort,assignment:RunnerAssignmentEnvelope){await port.deliver(assignment);}
function normalizeSubmission(value:unknown,ledger:Ledger){const input=plain(value);allowKeys(input,["status","findings","sources","provenance"]);const findings=array(input.findings),sources=array(input.sources);if(findings.length>ledger.quotas.maxFindings||sources.length>ledger.quotas.maxSources)throw reject();const normalizedSources=sources.map(item=>{const x=plain(item);allowKeys(x,["url","retrievedAt","excerpt","publisher"]);return{url:url(x.url),retrievedAt:time(x.retrievedAt),excerpt:text(x.excerpt,8192),publisher:text(x.publisher,512)}});const normalizedFindings=findings.map(item=>{const x=plain(item);allowKeys(x,["kind","sourceUrl","observedAt","excerpt"]);return{kind:text(x.kind,128),sourceUrl:url(x.sourceUrl),observedAt:time(x.observedAt),excerpt:text(x.excerpt,8192)}});const provenance=plain(input.provenance);allowKeys(provenance,["provider","model","instructionVersion","toolConfigurationDigest","tools","transformations"]);if(text(provenance.provider,256)!==ledger.provider||text(provenance.model,256)!==ledger.model||text(provenance.instructionVersion,256)!==ledger.instructionVersion||digest(provenance.toolConfigurationDigest)!==ledger.toolConfigurationDigest)throw reject();const tools=array(provenance.tools).map(x=>text(x,128));if(canonical([...tools].sort())!==canonical(ledger.allowedTools))throw reject();const transformations=array(provenance.transformations).map(x=>text(x,128));const normalized={schema:"runner-observations/v1",status:input.status==="partial"?"partial":"complete",findings:normalizedFindings,sources:normalizedSources,provenance:{provider:ledger.provider,model:ledger.model,instructionVersion:ledger.instructionVersion,toolConfigurationDigest:ledger.toolConfigurationDigest,tools,transformations}};if(new TextEncoder().encode(canonical(normalized)).byteLength>ledger.quotas.maxBytes)throw reject();return normalized;}
function validateIssue(i:IssueInput){if(!i.workspaceId||!i.runId||!i.profileId||!i.configurationId||!digestOk(i.configurationDigest)||!bounded(i.audience,128)||!bounded(i.instructionVersion,256)||!digestOk(i.toolConfigurationDigest)||!bounded(i.grantReference,256)||!bounded(i.reason,256)||!i.idempotencyKey||i.expiresAt<=i.now||!validQuotas(i.quotas)||i.capabilitySecret.byteLength<32)throw reject();}
function parseLedger(value:string):Ledger{try{const x=JSON.parse(value) as Ledger;if(!validQuotas(x.quotas)||!digestOk(x.toolConfigurationDigest)||!Array.isArray(x.allowedTools))throw Error();return{quotas:x.quotas,provider:bounded(x.provider,256),model:bounded(x.model,256),instructionVersion:bounded(x.instructionVersion,256),toolConfigurationDigest:x.toolConfigurationDigest,allowedTools:normalizeTools(x.allowedTools),grantReference:bounded(x.grantReference,256)}}catch{throw reject();}}
function validQuotas(x:Quotas){return!!x&&[x.maxBytes,x.maxFindings,x.maxSources].every(v=>Number.isSafeInteger(v)&&v>0)&&x.maxBytes<=1_048_576&&x.maxFindings<=500&&x.maxSources<=500;}
function normalizeTools(values:readonly string[]){if(values.length>32)throw reject();const out=values.map(v=>bounded(v,128)).sort();if(new Set(out).size!==out.length)throw reject();return out;}
function plain(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw reject();return v as Record<string,unknown>;} function array(v:unknown):unknown[]{if(!Array.isArray(v))throw reject();return v;} function allowKeys(v:Record<string,unknown>,keys:string[]){if(Object.keys(v).some(k=>!keys.includes(k)))throw reject();}
function text(v:unknown,max:number){return bounded(v,max)} function bounded(v:unknown,max:number){if(typeof v!=="string"||!(v=v.normalize("NFC").trim())||v.length>max)throw reject();return v;} function url(v:unknown){const p=new URL(text(v,2048));if(p.protocol!=="https:"||p.username||p.password)throw reject();p.hash="";return p.toString();} function time(v:unknown){if(!Number.isSafeInteger(v)||(v as number)<=0)throw reject();return v as number;} function digest(v:unknown){const x=text(v,64).toLowerCase();if(!digestOk(x))throw reject();return x;} function digestOk(v:unknown):v is string{return typeof v==="string"&&/^[0-9a-f]{64}$/.test(v)}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(",")}}`;}return JSON.stringify(v);} async function sha256(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,"0")).join("");}
function randomToken(){return toBase64Url(crypto.getRandomValues(new Uint8Array(32)));} async function signCapability(p:Capability,s:Uint8Array){const body=toBase64Url(new TextEncoder().encode(canonical(p))),key=await crypto.subtle.importKey("raw",s,{name:"HMAC",hash:"SHA-256"},false,["sign"]),signature=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(body));return`${body}.${toBase64Url(new Uint8Array(signature))}`;} async function verifyCapability(t:string,s:Uint8Array):Promise<Capability>{const[b,signature,extra]=t.split(".");if(!b||!signature||extra)throw reject();try{const key=await crypto.subtle.importKey("raw",s,{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,fromBase64Url(signature),new TextEncoder().encode(b)))throw Error();const p=JSON.parse(new TextDecoder().decode(fromBase64Url(b))) as Capability;if(!p||typeof p!=="object"||Object.keys(p).sort().join(",")!=="assignmentId,audience,configurationDigest,configurationId,expiresAt,nonce,profileId,runId,scope,workspaceId")throw Error();return p;}catch{throw reject();}} function toBase64Url(b:Uint8Array){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");} function fromBase64Url(v:string){const s=v.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-v.length%4)%4);return Uint8Array.from(atob(s),x=>x.charCodeAt(0));} function reject():RunnerAssignmentError{return new RunnerAssignmentError("runner_assignment_rejected");}
