import { v7 } from "uuid";

export class SourcePolicyError extends Error { readonly code="source_policy_rejected"; }
export type TrustedSourcePolicy=Readonly<{tier1Origins:readonly string[];tier2Origins:readonly string[];materialSignalKinds:readonly string[];publisherAliases?:Readonly<Record<string,string>>;underlyingOriginAliases?:Readonly<Record<string,string>>;independenceGroups?:Readonly<Record<string,string>>}>;
export type TrustedSourceObservation=Readonly<{url:string;retrievedAt:number;observedAt:number;excerpt:string;declaredPublisher?:string;kind:string;transformations?:readonly string[]}>;
export type ValidatedSignal=Readonly<{url:string;publisherIdentity:string;underlyingOriginIdentity:string;independenceGroup:string;tier:1|2|3;excerpt:string;retrievedAt:number;observedAt:number;kind:string;material:boolean;recency:"current"|"account_context_reconfirmation_required";fingerprint:string;transformations:readonly string[]}>;

/** This pure helper only accepts application-owned policy. Runner-declared tier and publisher are never authoritative. */
export async function validateSourceObservation(policy:TrustedSourcePolicy,observation:TrustedSourceObservation,now:number):Promise<ValidatedSignal>{
  const parsed=parseHttps(observation.url),host=registrableDomain(parsed.hostname),publisher=identity(policy.publisherAliases,host),underlying=identity(policy.underlyingOriginAliases,host),independence=identity(policy.independenceGroups,underlying);
  const tier=includesOrigin(policy.tier1Origins,underlying)?1:includesOrigin(policy.tier2Origins,underlying)?2:3,kind=bounded(observation.kind,"Signal kind",128),excerpt=escapedExcerpt(observation.excerpt),transformations=normalizeTransformations(observation.transformations??[]);
  if(!Number.isSafeInteger(observation.retrievedAt)||!Number.isSafeInteger(observation.observedAt)||observation.retrievedAt<=0||observation.observedAt<=0||observation.observedAt>observation.retrievedAt||observation.retrievedAt>now+60_000)throw fail();
  const material=policy.materialSignalKinds.map(x=>bounded(x,"Material signal kind",128)).includes(kind),recency=material&&now-observation.observedAt>THIRTY_DAYS?"account_context_reconfirmation_required" as const:"current" as const;
  const fingerprint=await digest(canonical({url:parsed.toString(),publisher,underlying,independence,kind,excerpt,observedAt:observation.observedAt,transformations}));
  return Object.freeze({url:parsed.toString(),publisherIdentity:publisher,underlyingOriginIdentity:underlying,independenceGroup:`origin:${independence}`,tier,excerpt,retrievedAt:observation.retrievedAt,observedAt:observation.observedAt,kind,material,recency,fingerprint,transformations});
}

/** Loads the immutable active Profile configuration; caller policy is intentionally not an authority input. */
export async function appendValidatedSignals(database:D1Database,input:{workspaceId:string;submissionId:string;now:number;policy?:TrustedSourcePolicy}){
  const submission=await database.prepare("SELECT s.id,s.run_id,s.assignment_id,s.configuration_id,s.submission_json,s.provenance_json,r.profile_id,r.configuration_digest FROM runner_submissions s JOIN prospecting_runs r ON r.id=s.run_id AND r.workspace_id=s.workspace_id WHERE s.id=? AND s.workspace_id=? LIMIT 1").bind(input.submissionId,input.workspaceId).first<{id:string;run_id:string;assignment_id:string;configuration_id:string;submission_json:string;provenance_json:string;profile_id:string;configuration_digest:string}>();
  if(!submission)throw fail(); const policy=await loadPinnedPolicy(database,input.workspaceId,submission.configuration_id,submission.profile_id,submission.configuration_digest);
  let payload:Record<string,unknown>,provenance:Record<string,unknown>;try{payload=parseObject(JSON.parse(submission.submission_json));provenance=parseObject(JSON.parse(submission.provenance_json));}catch{throw fail();}const findings=array(payload.findings),sources=array(payload.sources); const sourceByUrl=new Map<string,Record<string,unknown>>();
  for(const candidate of sources){const source=parseObject(candidate);const url=canonicalUrl(source.url);if(sourceByUrl.has(url))throw fail();sourceByUrl.set(url,source);}
  const inherited=normalizeTransformations(array(provenance.transformations).map(x=>bounded(x,"Transformation",128)));
  const validated=await Promise.all(findings.map(async finding=>{const item=parseObject(finding),source=sourceByUrl.get(canonicalUrl(item.sourceUrl));if(!source)throw fail();return validateSourceObservation(policy,{url:canonicalUrl(item.sourceUrl),retrievedAt:integer(source.retrievedAt),observedAt:integer(item.observedAt),excerpt:bounded(item.excerpt,"Runner source field",8192),kind:bounded(item.kind,"Runner source field",128),transformations:inherited},input.now);}));
  const sorted=[...validated].sort((a,b)=>a.fingerprint.localeCompare(b.fingerprint)); if(new Set(sorted.map(x=>x.fingerprint)).size!==sorted.length)throw fail();
  /* A submission is one atomic evidence contribution.  Multiple material facts
   * for the same identity would otherwise require an intra-batch predecessor. */
  const materialIdentities=sorted.filter(x=>x.material).map(x=>`${x.kind}\u0000${x.underlyingOriginIdentity}`);if(new Set(materialIdentities).size!==materialIdentities.length)throw fail();
  const already=await database.prepare("SELECT COUNT(*) count FROM prospecting_signals WHERE submission_id=? AND workspace_id=?").bind(submission.id,input.workspaceId).first<{count:number}>(); if(Number(already?.count??0))throw fail();
  /* D1 serializes the batch, but reads made before it do not serialize a
   * successor.  The guarded lineage INSERT below proves that the selected
   * predecessor is still the immediate latest fact when the write occurs. */
  for(let attempt=0;attempt<2;attempt++){const statements:D1PreparedStatement[]=[]; for(const signal of sorted){const lineageId=v7(),signalId=v7();
    const predecessor=signal.material?await database.prepare("SELECT ps.id,ps.signal_digest,ps.signal_json,pl.id lineage_id,pl.lineage_digest,pl.occurred_at FROM prospecting_signals ps JOIN prospecting_source_lineage pl ON pl.id=ps.source_lineage_id WHERE ps.workspace_id=? AND ps.profile_id=? AND ps.signal_kind=? AND ps.material=1 AND pl.underlying_origin_identity=? ORDER BY pl.occurred_at DESC,ps.id DESC LIMIT 1").bind(input.workspaceId,submission.profile_id,signal.kind,signal.underlyingOriginIdentity).first<{id:string;signal_digest:string;signal_json:string;lineage_id:string;lineage_digest:string;occurred_at:number}>():null;
    if(predecessor&&!validPredecessor(predecessor,signal))throw fail();
    const predecessorRef=predecessor?{relationType:"material_successor_reconfirmation/v1",predecessorSignalId:predecessor.id,predecessorSignalDigest:predecessor.signal_digest,predecessorLineageId:predecessor.lineage_id,predecessorLineageDigest:predecessor.lineage_digest,predecessorOccurredAt:Number(predecessor.occurred_at)}:null;
    const lineageJson=canonical({schema:"prospecting-source-lineage/v2",url:signal.url,publisherIdentity:signal.publisherIdentity,underlyingOriginIdentity:signal.underlyingOriginIdentity,independenceGroup:signal.independenceGroup,tier:signal.tier,retrievedAt:signal.retrievedAt,occurredAt:signal.observedAt,transformations:signal.transformations,assignmentId:submission.assignment_id,configurationId:submission.configuration_id,configurationDigest:submission.configuration_digest,submissionId:submission.id,successorOf:predecessorRef});const lineageDigest=await digest(lineageJson);
    const signalJson=canonical({schema:"prospecting-signal/v2",kind:signal.kind,excerpt:signal.excerpt,occurredAt:signal.observedAt,material:signal.material,recency:signal.recency,rawSubmissionId:submission.id,sourceLineageId:lineageId,sourceLineageDigest:lineageDigest,reconfirmation:predecessorRef,successorPolicy:"append_only"});const signalDigest=await digest(signalJson);
    const predecessorId=predecessor?.id??"",predecessorDigest=predecessor?.signal_digest??"",predecessorLineageId=predecessor?.lineage_id??"",predecessorLineageDigest=predecessor?.lineage_digest??"",predecessorOccurredAt=Number(predecessor?.occurred_at??0);
    const identity=[input.workspaceId,submission.profile_id,signal.kind,signal.underlyingOriginIdentity];
    statements.push(database.prepare("INSERT INTO prospecting_source_lineage (id,workspace_id,run_id,submission_id,source_id,source_url,publisher_identity,underlying_origin_identity,independence_group,source_tier,published_at,occurred_at,retrieved_at,excerpt,lineage_json,lineage_digest,created_at) SELECT ?,?,?,?,NULL,?,?,?,?,?,NULL,?,?,?,?,?,? WHERE ?=0 OR ?=1 AND NOT EXISTS (SELECT 1 FROM prospecting_signals ps JOIN prospecting_source_lineage pl ON pl.id=ps.source_lineage_id WHERE ps.workspace_id=? AND ps.profile_id=? AND ps.signal_kind=? AND ps.material=1 AND pl.underlying_origin_identity=?) OR ?=1 AND EXISTS (SELECT 1 FROM prospecting_signals ps JOIN prospecting_source_lineage pl ON pl.id=ps.source_lineage_id WHERE ps.id=? AND ps.signal_digest=? AND pl.id=? AND pl.lineage_digest=? AND pl.occurred_at=?) AND NOT EXISTS (SELECT 1 FROM prospecting_signals ps JOIN prospecting_source_lineage pl ON pl.id=ps.source_lineage_id WHERE ps.workspace_id=? AND ps.profile_id=? AND ps.signal_kind=? AND ps.material=1 AND pl.underlying_origin_identity=? AND (pl.occurred_at>? OR pl.occurred_at=? AND ps.id>?)) AND NOT EXISTS (SELECT 1 FROM prospecting_signals ps JOIN prospecting_source_lineage pl ON pl.id=ps.source_lineage_id WHERE ps.workspace_id=? AND ps.profile_id=? AND ps.signal_kind=? AND ps.material=1 AND pl.underlying_origin_identity=? AND pl.occurred_at>=?)").bind(lineageId,input.workspaceId,submission.run_id,submission.id,signal.url,signal.publisherIdentity,signal.underlyingOriginIdentity,signal.independenceGroup,signal.tier,signal.observedAt,signal.retrievedAt,signal.excerpt,lineageJson,lineageDigest,input.now,signal.material?1:0,predecessor?0:1,...identity,predecessor?1:0,predecessorId,predecessorDigest,predecessorLineageId,predecessorLineageDigest,predecessorOccurredAt,...identity,predecessorOccurredAt,predecessorOccurredAt,predecessorId,...identity,signal.observedAt),database.prepare("INSERT INTO prospecting_signals (id,workspace_id,run_id,submission_id,source_lineage_id,profile_id,signal_kind,signal_json,signal_digest,material,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM prospecting_source_lineage WHERE id=? AND workspace_id=?)").bind(signalId,input.workspaceId,submission.run_id,submission.id,lineageId,submission.profile_id,signal.kind,signalJson,signalDigest,signal.material?1:0,input.now,lineageId,input.workspaceId));}
    try{const results=statements.length?await database.batch(statements):[];if(results.every(x=>Number(x.meta?.changes??0)===1))return sorted;}catch{/* reload and evaluate the immutable latest predecessor below */}
    const winner=await database.prepare("SELECT COUNT(*) count FROM prospecting_signals WHERE submission_id=? AND workspace_id=?").bind(submission.id,input.workspaceId).first<{count:number}>();if(Number(winner?.count??0)===sorted.length)return sorted;
  } throw fail();
}

/** A successful window always overlaps its previous success watermark by exactly 24h. */
export function sourceWindow(watermark:number|null,upperInclusive:number){if(!Number.isSafeInteger(upperInclusive)||upperInclusive<=0||watermark!==null&&(!Number.isSafeInteger(watermark)||watermark>=upperInclusive))throw fail();return{lowerExclusive:watermark===null?null:watermark-TWENTY_FOUR_HOURS,upperInclusive};}
const TWENTY_FOUR_HOURS=24*60*60*1_000,THIRTY_DAYS=30*TWENTY_FOUR_HOURS;
async function loadPinnedPolicy(database:D1Database,workspaceId:string,configurationId:string,profileId:string,configurationDigest:string):Promise<TrustedSourcePolicy>{const row=await database.prepare("SELECT digest,manifest_json,active FROM typed_configurations WHERE id=? AND workspace_id=? AND owner_type='profile' AND owner_id=? AND kind='profile_effective' AND active=1 LIMIT 1").bind(configurationId,workspaceId,profileId).first<{digest:string;manifest_json:string;active:number}>();if(!row||!Number(row.active)||row.digest!==configurationDigest)throw fail();let manifest:Record<string,unknown>;try{manifest=parseObject(JSON.parse(row.manifest_json));}catch{throw fail();}const candidate=manifest.sourcePolicy??parseObjectOrNull(manifest.policy)?.sourcePolicy??parseObjectOrNull(manifest.authority)?.sourcePolicy;const policy=parseObject(candidate);const rules=parseObjectOrNull(policy.rules)??policy;if(typeof policy.id!=="string"||!validDigest(policy.digest))throw fail();return normalizePolicy(rules);}
function normalizePolicy(value:Record<string,unknown>):TrustedSourcePolicy{return{tier1Origins:array(value.tier1Origins).map(x=>bounded(x,"Policy origin",253)),tier2Origins:array(value.tier2Origins).map(x=>bounded(x,"Policy origin",253)),materialSignalKinds:array(value.materialSignalKinds).map(x=>bounded(x,"Material signal kind",128)),publisherAliases:map(value.publisherAliases),underlyingOriginAliases:map(value.underlyingOriginAliases),independenceGroups:map(value.independenceGroups)};}
function map(v:unknown):Record<string,string>{if(v===undefined)return{};const o=parseObject(v);return Object.fromEntries(Object.entries(o).map(([k,val])=>[registrableDomain(k),bounded(val,"Policy identity",253)]));}
function parseHttps(value:unknown){let p:URL;try{p=new URL(bounded(value,"Source URL",2048));}catch{throw fail();}if(p.protocol!=="https:"||p.username||p.password||p.port||p.hostname==="localhost"||isIp(p.hostname))throw fail();p.hash="";return p;} function canonicalUrl(v:unknown){return parseHttps(v).toString();} function isIp(h:string){return /^\d{1,3}(?:\.\d{1,3}){3}$/.test(h)||h.includes(":");}
/** Conservative PSL subset. Unknown ccTLD second-level conventions fail closed so
 * a host cannot borrow authority from an unrelated last-two-label domain. */
const MULTI_LABEL_SUFFIXES=new Set(["co.uk","org.uk","ac.uk","gov.uk","net.uk","com.au","net.au","org.au","edu.au","gov.au","co.nz","org.nz","govt.nz","com.br","com.mx","co.jp","ne.jp","or.jp","com.cn","net.cn","org.cn","com.sg","com.tr","co.in","firm.in","net.in","org.in"]);
const GENERIC_SUFFIXES=new Set(["com","net","org","edu","gov","io","ai","app","dev","info","biz","xyz","invalid","test","local"]);
function registrableDomain(host:string){const n=host.toLowerCase().replace(/\.$/,"");const labels=n.split(".");if(labels.length<2||labels.some(x=>!/^[a-z0-9-]{1,63}$/.test(x)))throw fail();const suffix2=labels.slice(-2).join(".");if(MULTI_LABEL_SUFFIXES.has(suffix2)){if(labels.length<3)throw fail();return labels.slice(-3).join(".");}const suffix=labels.at(-1)!;if(suffix.length===2){/* Bare ccTLD registries differ; only known explicit suffixes above are safe. */throw fail();}if(!GENERIC_SUFFIXES.has(suffix))throw fail();return suffix2;} function identity(m:Readonly<Record<string,string>>|undefined,fallback:string){return m?.[fallback]??fallback;} function includesOrigin(origins:readonly string[],origin:string){return origins.some(x=>registrableDomain(x)===origin);} function validPredecessor(p:{signal_json:string;occurred_at:number},next:ValidatedSignal){try{const old=parseObject(JSON.parse(p.signal_json));return old.material===true&&old.kind===next.kind&&Number.isSafeInteger(p.occurred_at)&&Number(p.occurred_at)<next.observedAt;}catch{return false;}} function escapedExcerpt(v:unknown){return bounded(v,"Source excerpt",8192).replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]!);} function normalizeTransformations(v:readonly string[]){if(v.length>16)throw fail();const x=v.map(a=>bounded(a,"Transformation",128)).sort();if(new Set(x).size!==x.length)throw fail();return x;} function bounded(v:unknown,_label:string,max:number){if(typeof v!=="string"||!(v=v.normalize("NFC").trim())||v.length>max)throw fail();return v;} function integer(v:unknown){if(!Number.isSafeInteger(v)||(v as number)<=0)throw fail();return v as number;} function array(v:unknown):unknown[]{if(!Array.isArray(v))throw fail();return v;} function parseObject(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw fail();return v as Record<string,unknown>;} function parseObjectOrNull(v:unknown){return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:null;} function validDigest(v:unknown):v is string{return typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);} function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(",")}}`;}return JSON.stringify(v);} async function digest(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,"0")).join("");} function fail():SourcePolicyError{return new SourcePolicyError("source_policy_rejected");}
