import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const auditColumns = {
  workspaceId: text("workspace_id").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  revision: integer("revision").notNull().default(1),
};

export const workspaces = sqliteTable("workspaces", {
  id: text("id").primaryKey(), companyName: text("company_name").notNull(), ownerSubject: text("owner_subject").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(), revision: integer("revision").notNull().default(1),
});

export const products = sqliteTable("products", { id: text("id").primaryKey(), ...auditColumns, name: text("name").notNull(), lifecycle: text("lifecycle", { enum: ["draft", "ready", "paused", "archived"] }).notNull() }, (t) => [index("products_workspace_idx").on(t.workspaceId)]);
export const marketPlays = sqliteTable("market_plays", { id: text("id").primaryKey(), ...auditColumns, productId: text("product_id").notNull(), name: text("name").notNull(), lifecycle: text("lifecycle", { enum: ["draft", "active", "paused", "archived"] }).notNull() }, (t) => [index("plays_product_idx").on(t.workspaceId, t.productId)]);
export const profiles = sqliteTable("customer_profiles", { id: text("id").primaryKey(), ...auditColumns, playId: text("play_id").notNull(), name: text("name").notNull(), lifecycle: text("lifecycle", { enum: ["draft", "ready", "paused", "archived"] }).notNull(), timezone: text("timezone").notNull(), weeklyTarget: integer("weekly_target").notNull().default(0) }, (t) => [index("profiles_play_idx").on(t.workspaceId, t.playId)]);

export const knowledgeVersions = sqliteTable("knowledge_versions", { id: text("id").primaryKey(), ...auditColumns, scopeType: text("scope_type", { enum: ["company", "product", "play", "profile"] }).notNull(), scopeId: text("scope_id").notNull(), kind: text("kind").notNull(), valueJson: text("value_json").notNull(), status: text("status", { enum: ["proposed", "confirmed", "rejected", "superseded"] }).notNull(), sourceDigest: text("source_digest") }, (t) => [index("knowledge_scope_idx").on(t.workspaceId, t.scopeType, t.scopeId)]);
export const configurations = sqliteTable("typed_configurations", { id: text("id").primaryKey(), ...auditColumns, ownerType: text("owner_type", { enum: ["product", "profile"] }).notNull(), ownerId: text("owner_id").notNull(), kind: text("kind", { enum: ["product_discovery", "profile_effective"] }).notNull(), digest: text("digest").notNull(), manifestJson: text("manifest_json").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(false) }, (t) => [uniqueIndex("config_digest_unique").on(t.workspaceId, t.kind, t.digest)]);

export const interviewSessions = sqliteTable("interview_sessions", { id: text("id").primaryKey(), ...auditColumns, scopeType: text("scope_type").notNull(), scopeId: text("scope_id").notNull(), state: text("state", { enum: ["open", "awaiting_answer", "awaiting_confirmation", "completed", "paused", "archived"] }).notNull(), activeQuestionId: text("active_question_id") }, (t) => [index("interview_session_scope_idx").on(t.workspaceId, t.scopeType, t.scopeId, t.state)]);
export const interviewQuestions = sqliteTable("interview_questions", { id: text("id").primaryKey(), ...auditColumns, sessionId: text("session_id").notNull().references(() => interviewSessions.id), version: integer("version").notNull(), prompt: text("prompt").notNull(), researchJson: text("research_json").notNull(), recommendation: text("recommendation"), status: text("status", { enum: ["draft", "active", "answered", "closed", "superseded"] }).notNull() }, (t) => [uniqueIndex("question_version_unique").on(t.workspaceId, t.sessionId, t.version)]);
export const interviewAnswers = sqliteTable("interview_answers", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), sessionId: text("session_id").notNull().references(() => interviewSessions.id), questionId: text("question_id").notNull().references(() => interviewQuestions.id), questionRevision: integer("question_revision").notNull(), choice: text("choice", { enum: ["accept_recommendation", "correct", "defer"] }).notNull(), correctionJson: text("correction_json"), idempotencyKey: text("idempotency_key").notNull(), operationDigest: text("operation_digest").notNull().default("legacy-unbound"), proposalJson: text("proposal_json").notNull().default("{}"), proposalDigest: text("proposal_digest").notNull().default("legacy-unbound"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("answer_question_unique").on(t.workspaceId, t.questionId), uniqueIndex("answer_idempotency_unique").on(t.workspaceId, t.idempotencyKey)]);
export const interviewConfirmations = sqliteTable("interview_confirmations", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), sessionId: text("session_id").notNull().references(() => interviewSessions.id), questionId: text("question_id").notNull().references(() => interviewQuestions.id), answerId: text("answer_id").notNull().references(() => interviewAnswers.id), decision: text("decision", { enum: ["accept", "reject", "correct", "rescope"] }).notNull(), knowledgeVersionId: text("knowledge_version_id").references(() => knowledgeVersions.id), idempotencyKey: text("idempotency_key").notNull(), operationDigest: text("operation_digest").notNull().default("legacy-unbound"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("confirmation_answer_unique").on(t.workspaceId, t.answerId), uniqueIndex("confirmation_idempotency_unique").on(t.workspaceId, t.idempotencyKey)]);

export const csrfTokens = sqliteTable("csrf_tokens", { id: text("id").primaryKey(), principalSubject: text("principal_subject").notNull(), tokenDigest: text("token_digest").notNull().unique(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), usedAt: integer("used_at", { mode: "timestamp_ms" }), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [index("csrf_principal_expiry_idx").on(t.principalSubject, t.expiresAt, t.usedAt)]);

export const importBatches = sqliteTable("import_batches", { id: text("id").primaryKey(), ...auditColumns, format: text("format").notNull(), formatVersion: text("format_version").notNull(), artifactDigestsJson: text("artifact_digests_json").notNull(), status: text("status", { enum: ["staged", "reviewing", "completed", "rejected"] }).notNull(), countsJson: text("counts_json").notNull() }, (t) => [uniqueIndex("import_identity_unique").on(t.workspaceId, t.format, t.formatVersion, t.artifactDigestsJson)]);
export const importItems = sqliteTable("import_items", { id: text("id").primaryKey(), ...auditColumns, batchId: text("batch_id").notNull(), sourceIndex: integer("source_index").notNull(), itemHash: text("item_hash").notNull(), destinationType: text("destination_type").notNull(), normalizedJson: text("normalized_json").notNull(), reviewState: text("review_state", { enum: ["unreviewed", "resolved", "promoted", "rejected"] }).notNull() }, (t) => [uniqueIndex("import_item_unique").on(t.workspaceId, t.batchId, t.sourceIndex)]);

export const prospects = sqliteTable("prospects", { id: text("id").primaryKey(), ...auditColumns, profileId: text("profile_id").notNull(), organizationName: text("organization_name").notNull(), targetName: text("target_name"), state: text("state").notNull(), score: integer("score"), configurationId: text("configuration_id").notNull() }, (t) => [index("prospect_queue_idx").on(t.workspaceId, t.profileId, t.state)]);
export const suppressions = sqliteTable("suppressions", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), subjectType: text("subject_type").notNull(), subjectDigest: text("subject_digest").notNull(), channel: text("channel").notNull(), reason: text("reason").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("suppression_subject_unique").on(t.workspaceId, t.subjectType, t.subjectDigest, t.channel)]);
export const auditEvents = sqliteTable("audit_events", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), actorType: text("actor_type").notNull(), actorId: text("actor_id").notNull(), action: text("action").notNull(), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), detailJson: text("detail_json").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [index("audit_workspace_time_idx").on(t.workspaceId, t.createdAt)]);
