import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const auditColumns = {
  workspaceId: text("workspace_id").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  revision: integer("revision").notNull().default(1),
};

export const workspaces = sqliteTable("workspaces", { id: text("id").primaryKey(), companyName: text("company_name").notNull(), ownerSubject: text("owner_subject").notNull().unique(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(), revision: integer("revision").notNull().default(1) });
export const companies = sqliteTable("companies", { id: text("id").primaryKey(), ...auditColumns, name: text("name").notNull(), status: text("status", { enum: ["draft", "active", "archived"] }).notNull().default("draft") }, (t) => [uniqueIndex("companies_workspace_unique").on(t.workspaceId)]);
export const workspaceCompanies = sqliteTable("workspace_companies", { workspaceId: text("workspace_id").primaryKey().references(() => workspaces.id), companyId: text("company_id").notNull().references(() => companies.id), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("workspace_companies_company_unique").on(t.companyId)]);

export const products = sqliteTable("products", { id: text("id").primaryKey(), ...auditColumns, companyId: text("company_id"), name: text("name").notNull(), lifecycle: text("lifecycle", { enum: ["draft", "ready", "paused", "archived"] }).notNull() }, (t) => [index("products_workspace_idx").on(t.workspaceId), index("products_company_idx").on(t.workspaceId, t.companyId)]);
export const marketPlays = sqliteTable("market_plays", { id: text("id").primaryKey(), ...auditColumns, productId: text("product_id").notNull().references(() => products.id), name: text("name").notNull(), lifecycle: text("lifecycle", { enum: ["draft", "active", "paused", "archived"] }).notNull() }, (t) => [index("plays_product_idx").on(t.workspaceId, t.productId)]);
export const profiles = sqliteTable("customer_profiles", { id: text("id").primaryKey(), ...auditColumns, playId: text("play_id").notNull().references(() => marketPlays.id), name: text("name").notNull(), lifecycle: text("lifecycle", { enum: ["draft", "ready", "paused", "archived"] }).notNull(), timezone: text("timezone").notNull(), weeklyTarget: integer("weekly_target").notNull().default(0) }, (t) => [index("profiles_play_idx").on(t.workspaceId, t.playId)]);
export const offers = sqliteTable("offers", { id: text("id").primaryKey(), ...auditColumns, profileId: text("profile_id").notNull().references(() => profiles.id), name: text("name").notNull(), valueJson: text("value_json").notNull(), questionId: text("question_id").notNull(), answerId: text("answer_id").notNull(), proposalId: text("proposal_id").notNull(), decisionId: text("decision_id").notNull(), knowledgeVersionId: text("knowledge_version_id").notNull(), authorityCommandId: text("authority_command_id").notNull(), auditEventId: text("audit_event_id").notNull() }, (t) => [index("offers_profile_idx").on(t.workspaceId, t.profileId), uniqueIndex("offers_authority_unique").on(t.authorityCommandId)]);

export const organizations = sqliteTable("organizations", { id: text("id").primaryKey(), ...auditColumns, companyId: text("company_id").notNull().references(() => companies.id), canonicalName: text("canonical_name").notNull(), identityDigest: text("identity_digest").notNull() }, (t) => [uniqueIndex("organization_company_identity_unique").on(t.workspaceId, t.companyId, t.identityDigest)]);
export const contacts = sqliteTable("contacts", { id: text("id").primaryKey(), ...auditColumns, companyId: text("company_id").notNull().references(() => companies.id), identityDigest: text("identity_digest").notNull(), displayName: text("display_name").notNull() }, (t) => [uniqueIndex("contact_company_identity_unique").on(t.workspaceId, t.companyId, t.identityDigest)]);
export const accounts = sqliteTable("accounts", { id: text("id").primaryKey(), ...auditColumns, playId: text("play_id").notNull().references(() => marketPlays.id), organizationId: text("organization_id").notNull().references(() => organizations.id), state: text("state", { enum: ["draft", "inactive", "archived"] }).notNull().default("draft") }, (t) => [uniqueIndex("account_play_organization_unique").on(t.workspaceId, t.playId, t.organizationId)]);
export const targets = sqliteTable("targets", { id: text("id").primaryKey(), ...auditColumns, profileId: text("profile_id").notNull().references(() => profiles.id), accountId: text("account_id").notNull().references(() => accounts.id), state: text("state", { enum: ["draft", "inactive", "archived"] }).notNull().default("draft") }, (t) => [uniqueIndex("target_profile_account_unique").on(t.workspaceId, t.profileId, t.accountId)]);
export const contactRelevance = sqliteTable("contact_relevance", { id: text("id").primaryKey(), ...auditColumns, playId: text("play_id").notNull().references(() => marketPlays.id), contactId: text("contact_id").notNull().references(() => contacts.id), relevanceJson: text("relevance_json").notNull() }, (t) => [uniqueIndex("contact_relevance_play_contact_unique").on(t.workspaceId, t.playId, t.contactId)]);

export const sources = sqliteTable("sources", { id: text("id").primaryKey(), ...auditColumns, origin: text("origin", { enum: ["public_research", "authorized_repository", "owner_import", "uploaded_quarantine", "reuse_package"] }).notNull(), opaqueLocator: text("opaque_locator").notNull(), sourceDigest: text("source_digest").notNull(), privacy: text("privacy", { enum: ["public", "private", "restricted"] }).notNull(), license: text("license").notNull(), status: text("status", { enum: ["available", "quarantined", "rejected"] }).notNull() }, (t) => [uniqueIndex("source_workspace_digest_unique").on(t.workspaceId, t.sourceDigest), uniqueIndex("source_workspace_locator_unique").on(t.workspaceId, t.opaqueLocator)]);
export const sourceExcerpts = sqliteTable("source_excerpts", { id: text("id").primaryKey(), ...auditColumns, sourceId: text("source_id").notNull().references(() => sources.id), excerptDigest: text("excerpt_digest").notNull(), content: text("content").notNull(), locator: text("locator").notNull() }, (t) => [uniqueIndex("source_excerpt_digest_unique").on(t.workspaceId, t.sourceId, t.excerptDigest)]);
export const sourceCustody = sqliteTable("source_custody", { id: text("id").primaryKey(), ...auditColumns, sourceId: text("source_id").notNull().references(() => sources.id), objectReference: text("object_reference").notNull(), quarantineStatus: text("quarantine_status", { enum: ["quarantined", "scan_pending", "scan_failed"] }).notNull(), scanStatus: text("scan_status", { enum: ["not_scanned", "pending", "failed"] }).notNull(), objectDigest: text("object_digest").notNull() }, (t) => [uniqueIndex("source_custody_object_unique").on(t.workspaceId, t.objectReference)]);
export const researchCandidates = sqliteTable("research_candidates", { id: text("id").primaryKey(), ...auditColumns, sourceId: text("source_id").notNull().references(() => sources.id), excerptId: text("excerpt_id").notNull().references(() => sourceExcerpts.id), opaqueLocator: text("opaque_locator").notNull(), provenanceDigest: text("provenance_digest").notNull(), visibility: text("visibility", { enum: ["public", "authorized"] }).notNull(), status: text("status", { enum: ["available", "withdrawn"] }).notNull() }, (t) => [uniqueIndex("research_candidate_locator_unique").on(t.workspaceId, t.opaqueLocator)]);

export const knowledgeItems = sqliteTable("knowledge_items", { id: text("id").primaryKey(), ...auditColumns, companyId: text("company_id").notNull().references(() => companies.id), scopeType: text("scope_type", { enum: ["company", "product", "play", "profile", "offer"] }).notNull(), scopeId: text("scope_id").notNull(), kind: text("kind").notNull(), slot: text("slot").notNull().default("default"), currentVersionId: text("current_version_id") }, (t) => [uniqueIndex("knowledge_item_scope_unique").on(t.workspaceId, t.scopeType, t.scopeId, t.kind, t.slot), uniqueIndex("knowledge_item_current_version_unique").on(t.currentVersionId)]);
export const knowledgeVersions = sqliteTable("knowledge_versions", { id: text("id").primaryKey(), ...auditColumns, knowledgeItemId: text("knowledge_item_id").references(() => knowledgeItems.id), proposalId: text("proposal_id"), decisionId: text("decision_id"), authorityCommandId: text("authority_command_id"), scopeType: text("scope_type", { enum: ["company", "product", "play", "profile", "offer"] }).notNull(), scopeId: text("scope_id").notNull(), kind: text("kind").notNull(), valueJson: text("value_json").notNull(), valueDigest: text("value_digest"), status: text("status", { enum: ["proposed", "confirmed", "rejected", "superseded"] }).notNull(), sourceDigest: text("source_digest") }, (t) => [index("knowledge_scope_idx").on(t.workspaceId, t.scopeType, t.scopeId), uniqueIndex("knowledge_current_version_item_unique").on(t.knowledgeItemId).where(undefined)]);
export const knowledgeProposals = sqliteTable("knowledge_proposals", { id: text("id").primaryKey(), ...auditColumns, companyId: text("company_id").notNull().references(() => companies.id), sourceId: text("source_id").references(() => sources.id), excerptId: text("excerpt_id").references(() => sourceExcerpts.id), destinationScopeType: text("destination_scope_type").notNull(), destinationScopeId: text("destination_scope_id").notNull(), kind: text("kind").notNull(), valueJson: text("value_json").notNull(), provenanceJson: text("provenance_json").notNull(), proposalDigest: text("proposal_digest").notNull(), origin: text("origin", { enum: ["research", "import", "upload", "owner_edit", "reuse"] }).notNull(), status: text("status", { enum: ["proposed", "reviewed", "rejected", "superseded"] }).notNull().default("proposed") }, (t) => [uniqueIndex("knowledge_proposal_digest_unique").on(t.workspaceId, t.proposalDigest)]);
export const authorityCommands = sqliteTable("authority_commands", { id: text("id").primaryKey(), ...auditColumns, commandType: text("command_type").notNull(), idempotencyKey: text("idempotency_key").notNull(), operationDigest: text("operation_digest").notNull(), expectedRevision: integer("expected_revision").notNull(), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), status: text("status", { enum: ["accepted", "superseded"] }).notNull().default("accepted") }, (t) => [uniqueIndex("authority_command_key_unique").on(t.workspaceId, t.idempotencyKey), uniqueIndex("authority_command_digest_unique").on(t.workspaceId, t.operationDigest)]);
export const proposalDecisions = sqliteTable("proposal_decisions", { id: text("id").primaryKey(), ...auditColumns, proposalId: text("proposal_id").notNull().references(() => knowledgeProposals.id), answerId: text("answer_id").references(() => interviewAnswers.id), authorityCommandId: text("authority_command_id").notNull().references(() => authorityCommands.id), decision: text("decision", { enum: ["accept", "reject", "correct", "rescope"] }).notNull(), reviewedSnapshotDigest: text("reviewed_snapshot_digest").notNull(), operationDigest: text("operation_digest").notNull(), idempotencyKey: text("idempotency_key").notNull() }, (t) => [uniqueIndex("proposal_decision_proposal_unique").on(t.proposalId), uniqueIndex("proposal_decision_key_unique").on(t.workspaceId, t.idempotencyKey), uniqueIndex("proposal_decision_snapshot_unique").on(t.workspaceId, t.reviewedSnapshotDigest)]);
export const proposalPrerequisites = sqliteTable("proposal_prerequisites", { proposalId: text("proposal_id").notNull().references(() => knowledgeProposals.id), knowledgeVersionId: text("knowledge_version_id").notNull().references(() => knowledgeVersions.id), prerequisiteDigest: text("prerequisite_digest").notNull() }, (t) => [uniqueIndex("proposal_prerequisite_unique").on(t.proposalId, t.knowledgeVersionId)]);

export const interviewSessions = sqliteTable("interview_sessions", { id: text("id").primaryKey(), ...auditColumns, companyId: text("company_id"), scopeType: text("scope_type").notNull(), scopeId: text("scope_id").notNull(), state: text("state", { enum: ["open", "awaiting_answer", "awaiting_confirmation", "completed", "paused", "archived"] }).notNull(), activeQuestionId: text("active_question_id") }, (t) => [index("interview_session_scope_idx").on(t.workspaceId, t.scopeType, t.scopeId, t.state), uniqueIndex("live_interview_destination_unique").on(t.workspaceId, t.scopeType, t.scopeId).where(sql`${t.state} in ('open', 'awaiting_answer', 'awaiting_confirmation', 'paused')`)]);
export const interviewQuestions = sqliteTable("interview_questions", { id: text("id").primaryKey(), ...auditColumns, sessionId: text("session_id").notNull().references(() => interviewSessions.id), version: integer("version").notNull(), prompt: text("prompt").notNull(), researchJson: text("research_json").notNull(), recommendation: text("recommendation"), status: text("status", { enum: ["draft", "active", "answered", "closed", "superseded"] }).notNull() }, (t) => [uniqueIndex("question_version_unique").on(t.workspaceId, t.sessionId, t.version)]);
export const interviewAnswers = sqliteTable("interview_answers", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), sessionId: text("session_id").notNull().references(() => interviewSessions.id), questionId: text("question_id").notNull().references(() => interviewQuestions.id), questionRevision: integer("question_revision").notNull(), choice: text("choice", { enum: ["accept_recommendation", "correct", "defer"] }).notNull(), correctionJson: text("correction_json"), idempotencyKey: text("idempotency_key").notNull(), operationDigest: text("operation_digest").notNull().default("legacy-unbound"), proposalJson: text("proposal_json").notNull().default("{}"), proposalDigest: text("proposal_digest").notNull().default("legacy-unbound"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("answer_question_unique").on(t.workspaceId, t.questionId), uniqueIndex("answer_idempotency_unique").on(t.workspaceId, t.idempotencyKey)]);
export const interviewConfirmations = sqliteTable("interview_confirmations", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), sessionId: text("session_id").notNull().references(() => interviewSessions.id), questionId: text("question_id").notNull().references(() => interviewQuestions.id), answerId: text("answer_id").notNull().references(() => interviewAnswers.id), decision: text("decision", { enum: ["accept", "reject", "correct", "rescope"] }).notNull(), knowledgeVersionId: text("knowledge_version_id").references(() => knowledgeVersions.id), idempotencyKey: text("idempotency_key").notNull(), operationDigest: text("operation_digest").notNull().default("legacy-unbound"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("confirmation_answer_unique").on(t.workspaceId, t.answerId), uniqueIndex("confirmation_idempotency_unique").on(t.workspaceId, t.idempotencyKey)]);
export const interviewAuthorityBindings = sqliteTable("interview_authority_bindings", { answerId: text("answer_id").primaryKey().references(() => interviewAnswers.id), confirmationId: text("confirmation_id").notNull().references(() => interviewConfirmations.id), knowledgeVersionId: text("knowledge_version_id").notNull().references(() => knowledgeVersions.id), knowledgeItemId: text("knowledge_item_id").notNull().references(() => knowledgeItems.id), proposalId: text("proposal_id"), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() });
export const interviewAuthorityReview = sqliteTable("interview_authority_review", { answerId: text("answer_id").primaryKey().references(() => interviewAnswers.id), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), status: text("status", { enum: ["review_required", "resolved"] }).notNull(), reason: text("reason").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() });

export const configurations = sqliteTable("typed_configurations", { id: text("id").primaryKey(), ...auditColumns, companyId: text("company_id"), ownerType: text("owner_type", { enum: ["product", "profile"] }).notNull(), ownerId: text("owner_id").notNull(), kind: text("kind", { enum: ["product_discovery", "profile_effective"] }).notNull(), digest: text("digest").notNull(), manifestJson: text("manifest_json").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(false) }, (t) => [uniqueIndex("config_digest_unique").on(t.workspaceId, t.kind, t.digest), uniqueIndex("active_configuration_owner_unique").on(t.workspaceId, t.ownerType, t.ownerId, t.kind).where(sql`${t.active} = 1`), index("config_owner_idx").on(t.workspaceId, t.ownerType, t.ownerId)]);
export const configurationKnowledgeDependencies = sqliteTable("configuration_knowledge_dependencies", { configurationId: text("configuration_id").notNull().references(() => configurations.id), knowledgeVersionId: text("knowledge_version_id").notNull().references(() => knowledgeVersions.id), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("configuration_knowledge_dependency_unique").on(t.configurationId, t.knowledgeVersionId)]);
export const artifactConfigurationDependencies = sqliteTable("artifact_configuration_dependencies", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), artifactType: text("artifact_type").notNull(), artifactId: text("artifact_id").notNull(), configurationId: text("configuration_id").notNull().references(() => configurations.id), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("artifact_configuration_dependency_unique").on(t.workspaceId, t.artifactType, t.artifactId, t.configurationId)]);
export const knowledgeDrifts = sqliteTable("knowledge_drifts", { id: text("id").primaryKey(), ...auditColumns, knowledgeItemId: text("knowledge_item_id").notNull().references(() => knowledgeItems.id), currentVersionId: text("current_version_id").notNull().references(() => knowledgeVersions.id), proposalId: text("proposal_id").notNull().references(() => knowledgeProposals.id), riskKind: text("risk_kind", { enum: ["capability", "proof_point", "claim_guardrail", "offer", "suppression", "standard"] }).notNull(), dependencyDigest: text("dependency_digest").notNull(), status: text("status", { enum: ["open", "reviewed", "contained", "resolved"] }).notNull() });
export const driftImpactSnapshots = sqliteTable("drift_impact_snapshots", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), driftId: text("drift_id").notNull().references(() => knowledgeDrifts.id), impactJson: text("impact_json").notNull(), impactDigest: text("impact_digest").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("drift_impact_digest_unique").on(t.driftId, t.impactDigest)]);
export const replacementCandidates = sqliteTable("replacement_candidates", { id: text("id").primaryKey(), ...auditColumns, ownerType: text("owner_type").notNull(), ownerId: text("owner_id").notNull(), currentConfigurationId: text("current_configuration_id").references(() => configurations.id), candidateConfigurationId: text("candidate_configuration_id").notNull().references(() => configurations.id), impactSnapshotId: text("impact_snapshot_id").notNull().references(() => driftImpactSnapshots.id), candidateDigest: text("candidate_digest").notNull(), status: text("status", { enum: ["proposed", "activated", "superseded", "cancelled"] }).notNull().default("proposed") }, (t) => [uniqueIndex("replacement_candidate_digest_unique").on(t.workspaceId, t.candidateDigest)]);
export const configurationActivations = sqliteTable("configuration_activations", { id: text("id").primaryKey(), ...auditColumns, replacementCandidateId: text("replacement_candidate_id").notNull().references(() => replacementCandidates.id), authorityCommandId: text("authority_command_id").notNull().references(() => authorityCommands.id), previousConfigurationId: text("previous_configuration_id").references(() => configurations.id), nextConfigurationId: text("next_configuration_id").notNull().references(() => configurations.id), expectedOwnerRevision: integer("expected_owner_revision").notNull(), operationDigest: text("operation_digest").notNull() }, (t) => [uniqueIndex("configuration_activation_candidate_unique").on(t.replacementCandidateId), uniqueIndex("configuration_activation_command_unique").on(t.authorityCommandId)]);
export const phaseActivationGates = sqliteTable("phase_activation_gates", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull().references(() => workspaces.id), capability: text("capability", { enum: ["consensus_knowledge"] }).notNull(), authorizationReference: text("authorization_reference").notNull(), targetProjectDeployment: text("target_project_deployment").notNull(), reviewedSourceDigest: text("reviewed_source_digest").notNull(), migrationIdentityStatus: text("migration_identity_status").notNull(), postMigrationEvidenceReference: text("post_migration_evidence_reference").notNull(), independentReviewReference: text("independent_review_reference").notNull(), deployedBoundaryProofReference: text("deployed_boundary_proof_reference").notNull(), tupleDigest: text("tuple_digest").notNull(), acceptedAt: integer("accepted_at", { mode: "timestamp_ms" }).notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("phase_gate_capability_unique").on(t.workspaceId, t.capability), uniqueIndex("phase_gate_tuple_unique").on(t.workspaceId, t.capability, t.tupleDigest)]);

export const csrfTokens = sqliteTable("csrf_tokens", { id: text("id").primaryKey(), principalSubject: text("principal_subject").notNull(), tokenDigest: text("token_digest").notNull().unique(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), usedAt: integer("used_at", { mode: "timestamp_ms" }), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [index("csrf_principal_expiry_idx").on(t.principalSubject, t.expiresAt, t.usedAt)]);
export const importBatches = sqliteTable("import_batches", { id: text("id").primaryKey(), ...auditColumns, format: text("format").notNull(), formatVersion: text("format_version").notNull(), artifactDigestsJson: text("artifact_digests_json").notNull(), status: text("status", { enum: ["staged", "reviewing", "completed", "rejected"] }).notNull(), countsJson: text("counts_json").notNull() }, (t) => [uniqueIndex("import_identity_unique").on(t.workspaceId, t.format, t.formatVersion, t.artifactDigestsJson)]);
export const importItems = sqliteTable("import_items", { id: text("id").primaryKey(), ...auditColumns, batchId: text("batch_id").notNull(), sourceIndex: integer("source_index").notNull(), itemHash: text("item_hash").notNull(), destinationType: text("destination_type").notNull(), normalizedJson: text("normalized_json").notNull(), reviewState: text("review_state", { enum: ["unreviewed", "resolved", "promoted", "rejected"] }).notNull() }, (t) => [uniqueIndex("import_item_unique").on(t.workspaceId, t.batchId, t.sourceIndex)]);
export const prospects = sqliteTable("prospects", { id: text("id").primaryKey(), ...auditColumns, profileId: text("profile_id").notNull(), organizationName: text("organization_name").notNull(), targetName: text("target_name"), state: text("state").notNull(), score: integer("score"), configurationId: text("configuration_id").notNull() }, (t) => [index("prospect_queue_idx").on(t.workspaceId, t.profileId, t.state)]);
export const suppressions = sqliteTable("suppressions", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), subjectType: text("subject_type").notNull(), subjectDigest: text("subject_digest").notNull(), channel: text("channel").notNull(), reason: text("reason").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("suppression_subject_unique").on(t.workspaceId, t.subjectType, t.subjectDigest, t.channel)]);
export const auditEvents = sqliteTable("audit_events", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), actorType: text("actor_type").notNull(), actorId: text("actor_id").notNull(), action: text("action").notNull(), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), detailJson: text("detail_json").notNull(), createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull() }, (t) => [index("audit_workspace_time_idx").on(t.workspaceId, t.createdAt)]);
