"use client";

import { useEffect, useRef, useState } from "react";
import type { InterviewDestination, InterviewState } from "../../domain/interview";

export type InterviewAnswerCommand = { questionId: string; expectedRevision: number; answer: "use_recommendation" | "write_correction" | "change_scope"; value?: string; reason?: string; destination?: InterviewDestination; operationKey: string };
export type InterviewDecisionCommand = { answerId: string; expectedSessionRevision: number; expectedQuestionRevision: number; decision: "accept" | "reject" | "correct" | "rescope"; value?: string; reason?: string; destination?: InterviewDestination; operationKey: string };

export function ConsensusInterviewView({ state, answerOperationKey, decisionOperationKey, onSubmitAnswer, onRecordDecision, issue }: { state: InterviewState; answerOperationKey: string; decisionOperationKey: string; onSubmitAnswer(command: InterviewAnswerCommand): void; onRecordDecision(command: InterviewDecisionCommand): void; issue?: "stale" | "other_tab" | "superseded" | "network_unknown" | "malformed" | null }) {
  const confirmationHeading = useRef<HTMLHeadingElement>(null); const [answer, setAnswer] = useState<InterviewAnswerCommand["answer"]>("use_recommendation"); const [value, setValue] = useState(""); const [reason, setReason] = useState(""); const [decision, setDecision] = useState<InterviewDecisionCommand["decision"] | null>(null);
  useEffect(() => { if (state.status === "awaiting_confirmation") confirmationHeading.current?.focus(); }, [state.status]);
  if (issue) return <section className="error-state" role="alert"><h2>Current authority needs checking</h2><p>{issueCopy(issue)}</p><button type="button" className="outline">Check current version</button></section>;
  if (state.status === "uninitialized") return <section className="panel"><h2>Interview unavailable</h2><p>Initialize the admitted commercial workspace before reviewing authority.</p></section>;
  if (state.status === "review_required") return <section className="panel" role="alert"><h2>Review required</h2><p>An earlier decision has no complete immutable snapshot. It is read-only until the workspace provides a replacement review.</p></section>;
  if (state.status === "confirmed") return <section className="panel" aria-live="polite"><h2>Confirmed result</h2><p>Authoritative result recorded. No operational effect has been enabled.</p><dl className="confirmation-proof"><div><dt>Knowledge Version</dt><dd>{state.confirmed.knowledgeVersionId}</dd></div><div><dt>Audit reference</dt><dd>{state.confirmed.auditEventId}</dd></div><div><dt>Confirmed (Toronto)</dt><dd>{toronto(state.confirmed.confirmedAt)}</dd></div></dl></section>;
  const destination: InterviewDestination = { scopeType: "company", locator: state.workspace.companyName };
  if (state.status === "active") return <section className="panel question-card"><span className="question-number">QUESTION 1 / 1 · COMPANY · REVISION {state.question.revision}</span><p>Destination: {destination.locator}. Prerequisites: none recorded.</p><h2>{state.question.prompt}</h2><section><h3>Evidence</h3><article><b>Source</b><p>{state.question.provenance}</p><p>Retrieved: not recorded · Ref: server projection</p><p>{state.question.premise}</p></article></section><section><h3>Inference</h3><p>This is an inference, not a sourced fact.</p><p>{state.question.inference}</p></section><section className="recommendation"><h3>Recommendation</h3><p>{state.question.recommendation}</p></section><fieldset><legend>Your answer</legend>{(["use_recommendation", "write_correction", "change_scope"] as const).map((choice) => <label key={choice}><input type="radio" name="interview-answer" checked={answer === choice} onChange={() => setAnswer(choice)} />{choice === "use_recommendation" ? "Use recommendation" : choice === "write_correction" ? "Write correction" : "Change scope"}</label>)}{answer !== "use_recommendation" && <><label>{answer === "write_correction" ? "Corrected value" : "Destination path"}<input required value={value} onChange={(event) => setValue(event.target.value)} /></label><label>Reason<textarea required value={reason} onChange={(event) => setReason(event.target.value)} /></label></>}</fieldset><button className="primary" type="button" onClick={() => onSubmitAnswer({ questionId: state.question.id, expectedRevision: state.question.revision, answer, ...(answer !== "use_recommendation" ? { value, reason } : {}), ...(answer === "change_scope" ? { destination: { ...destination, locator: value } } : {}), operationKey: answerOperationKey })}>Submit answer for confirmation</button><p className="saved">Saving an answer does not create Confirmed Knowledge. A separate owner confirmation is required.</p></section>;
  return <section className="panel question-card"><span className="question-number">QUESTION 1 / 1 · REVISION {state.question.revision}</span><h2 ref={confirmationHeading} tabIndex={-1}>Confirm submitted answer</h2><p>This action is separate from answer submission and is recorded against the exact snapshot shown.</p><dl className="confirmation-proof"><div><dt>Stored answer / proposal digest</dt><dd>{state.answer.operationDigest}</dd></div><div><dt>Question revision</dt><dd>{state.question.revision}</dd></div><div><dt>Destination</dt><dd>{destination.locator}</dd></div><div><dt>Prerequisites</dt><dd>None recorded</dd></div></dl>{state.question.id === "hierarchy_completion_offer" && <p>No Offer exists yet. Only Accept, Correct, or Rescope of this exact stored proposal creates the first Offer under the displayed Customer Profile. Reject creates none.</p>}<fieldset><legend>Owner decision</legend>{(["accept", "reject", "correct", "rescope"] as const).map((choice) => <label key={choice}><input type="radio" name="interview-decision" checked={decision === choice} onChange={() => setDecision(choice)} />{choice[0].toUpperCase() + choice.slice(1)}</label>)}{(decision === "correct" || decision === "rescope") && <><label>{decision === "correct" ? "Corrected value" : "Destination path"}<input required value={value} onChange={(event) => setValue(event.target.value)} /></label><label>Reason<textarea required value={reason} onChange={(event) => setReason(event.target.value)} /></label></>}</fieldset><button className="primary" type="button" disabled={!decision} onClick={() => decision && onRecordDecision({ answerId: state.answer.id, expectedSessionRevision: state.session.revision, expectedQuestionRevision: state.question.revision, decision, ...(decision === "correct" || decision === "rescope" ? { value, reason } : {}), ...(decision === "rescope" ? { destination: { ...destination, locator: value } } : {}), operationKey: decisionOperationKey })}>{decision === "correct" ? "Record correction" : decision === "rescope" ? "Record rescope" : decision === "accept" ? "Accept" : "Reject"}</button></section>;
}
function issueCopy(issue: NonNullable<Parameters<typeof ConsensusInterviewView>[0]["issue"]>) { return issue === "network_unknown" ? "The result is unknown. No action was retried." : issue === "malformed" ? "The server projection was incomplete; mutation controls are hidden." : "Another owner action may have changed this snapshot. Refresh before acting."; }
function toronto(value: number) { return new Date(value).toLocaleString("en-CA", { timeZone: "America/Toronto", dateStyle: "medium", timeStyle: "short" }); }
