"use client";

import type { ReachedArtifact } from "../../domain/drift";

export type DriftProjection = { id: string; riskKind: string; status: string; currentValue?: string; proposedValue?: string; provenance?: string; paths?: readonly string[]; artifacts?: readonly ReachedArtifact[]; impactDigest: string; candidate?: Omit<ReplacementCandidateCommand, "operationKey"> };
export type ReplacementProjection = { id: string; revision: number; status: string; currentConfigurationId?: string; candidateConfigurationId?: string; impactDigest?: string; proposedVersionId?: string; expectedOwnerRevision?: number; activatedAt?: number; activatedBy?: string; auditEventId?: string; immutable?: true };
export type ReplacementCandidateCommand = { currentVersionId: string; proposedVersionId: string; ownerType: "product" | "profile"; ownerId: string; kind: "product_discovery" | "profile_effective"; expectedOwnerRevision: number; operationKey: string };
export type ReplacementActivationCommand = { candidateId: string; impactDigest: string; expectedOwnerRevision: number; expectedCandidateRevision: number; operationKey: string };

export function DriftReplacementsView({ drift, candidates, operationKey, onCreateCandidate, onActivateReplacement, pendingAction, issue }: { drift: readonly DriftProjection[]; candidates: readonly ReplacementProjection[]; operationKey: string; onCreateCandidate(command: ReplacementCandidateCommand): void; onActivateReplacement(command: ReplacementActivationCommand): void; pendingAction?: string | null; issue?: string | null }) {
  if (issue) return <section className="error-state" role="alert">Drift authority is unknown: {issue}. Candidate and activation controls are hidden until the current version can be checked.</section>;
  const unresolved = drift.filter((item) => item.status !== "resolved"); const resolved = drift.filter((item) => item.status === "resolved");
  return <section className="drift-replacements-view"><section className="panel"><h2>Drift &amp; Replacements</h2><p>Unresolved drift appears first. A candidate is not active; activation is a separate exact-digest decision.</p></section>{unresolved.map((item) => <DriftCard key={item.id} item={item} operationKey={operationKey} onCreateCandidate={onCreateCandidate} pendingAction={pendingAction} />)}{!unresolved.length && <section className="panel"><h3>No unresolved knowledge drift</h3><p>Confirmed Knowledge and active configurations have no projected differences requiring owner review.</p></section>}<section aria-label="Replacement candidates">{candidates.map((candidate) => <CandidateCard key={candidate.id} candidate={candidate} operationKey={operationKey} onActivateReplacement={onActivateReplacement} pendingAction={pendingAction} />)}</section><details><summary>Resolved drift and activation history ({resolved.length})</summary>{resolved.map((item) => <DriftCard key={item.id} item={item} operationKey={operationKey} onCreateCandidate={onCreateCandidate} pendingAction={pendingAction} />)}</details></section>;
}
function DriftCard({ item, operationKey, onCreateCandidate, pendingAction }: { item: DriftProjection; operationKey: string; onCreateCandidate(command: ReplacementCandidateCommand): void; pendingAction?: string | null }) { const highRisk = ["capability", "proof_point", "claim_guardrail", "offer", "suppression"].includes(item.riskKind); const artifacts = item.artifacts ?? []; const containment = highRisk && artifacts.some((artifact) => artifact.status !== "not_present") ? "Affected outbound paused" : highRisk ? "Operational effects remain disabled in this pilot" : "No operational effect"; return <article className="panel"><span className={highRisk ? "drift-risk drift-risk--high" : "drift-risk"}>{highRisk ? "High-risk drift" : "Standard drift"} · {item.riskKind}</span><h2>Knowledge Drift {item.id}</h2><dl className="confirmation-proof"><div><dt>Current / proposed</dt><dd>{item.currentValue ?? "Not included in projection"} / {item.proposedValue ?? "Not included in projection"}</dd></div><div><dt>Source / provenance</dt><dd>{item.provenance ?? "Not included in projection"}</dd></div><div><dt>Dependency path</dt><dd>{item.paths?.join(" -> ") ?? "Not included in projection"}</dd></div><div><dt>Containment</dt><dd>{containment}</dd></div></dl><h3>Impact preview</h3>{artifacts.length ? <ul>{artifacts.map((artifact) => <li key={`${artifact.artifactType}:${artifact.artifactId}`}>{artifact.artifactType} / {artifact.status}: {artifact.artifactId}</li>)}</ul> : <p>No reached artifacts are included in this projection.</p>}<p>Reached artifacts: {artifacts.length}. Exact impact digest: <code>{item.impactDigest}</code></p><button className="primary" type="button" disabled={!item.candidate} onClick={() => item.candidate && onCreateCandidate({ ...item.candidate, operationKey })}>{pendingAction?.startsWith("candidate:") ? "Creating replacement candidate…" : "Create replacement candidate"}</button>{!item.candidate && <p className="saved">Available after the server returns the exact candidate scope, versions, dependency impact, and expected revision.</p>}<p className="contract-gap" role="note">Owner review is unavailable because this server projection does not include the proposal ID, proposal revision, exact destination, or a drift-review command binding needed for genuine Accept, Reject, Correct, and Rescope decisions. Candidate creation cannot substitute for that review or activate a configuration.</p></article>; }
function CandidateCard({ candidate, operationKey, onActivateReplacement, pendingAction }: { candidate: ReplacementProjection; operationKey: string; onActivateReplacement(command: ReplacementActivationCommand): void; pendingAction?: string | null }) { const active = candidate.status === "activated"; const activationReady = !active && Boolean(candidate.currentConfigurationId && candidate.candidateConfigurationId && candidate.impactDigest && candidate.proposedVersionId && candidate.expectedOwnerRevision); return <article className="panel"><span className={active ? "knowledge-status knowledge-status--confirmed" : "knowledge-status knowledge-status--proposed"}>{active ? "Replacement active" : "Candidate — not active"}</span><h2>Replacement candidate</h2><dl className="confirmation-proof"><div><dt>Proposed Knowledge Version</dt><dd>{candidate.proposedVersionId ?? "Not included in projection"}</dd></div><div><dt>Candidate configuration</dt><dd>{candidate.candidateConfigurationId ?? "Not included in projection"}</dd></div><div><dt>Preserved prior snapshot</dt><dd>{candidate.currentConfigurationId ?? "Not included in projection"}</dd></div><div><dt>Exact impact digest</dt><dd>{candidate.impactDigest ?? "Not included in projection"}</dd></div>{active && <><div><dt>Activated (Toronto)</dt><dd>{candidate.activatedAt ? toronto(candidate.activatedAt) : "Not included in projection"}</dd></div><div><dt>Owner</dt><dd>{candidate.activatedBy ?? "Not included in projection"}</dd></div><div><dt>Audit reference</dt><dd>{candidate.auditEventId ?? "Not included in projection"}</dd></div></>}</dl>{!active && <><h3>Activation boundary</h3><p>Activation preserves the current snapshot as history, moves future work to this immutable replacement, and invalidates only the dependent approvals shown above. It does not authorize any later operational effect.</p><button className="primary" type="button" disabled={!activationReady} onClick={() => activationReady && onActivateReplacement({ candidateId: candidate.id, impactDigest: candidate.impactDigest!, expectedOwnerRevision: candidate.expectedOwnerRevision!, expectedCandidateRevision: candidate.revision, operationKey })}>{pendingAction === `activate:${candidate.id}` ? "Activating replacement…" : "Activate replacement"}</button>{!activationReady && <p className="contract-gap" role="note">Activation is unavailable because the server projection does not include the current/candidate configuration references, proposed Knowledge Version, exact impact digest, and current owner revision required by this exact-snapshot command.</p>}</>}</article>; }
function toronto(value: number) { return new Date(value).toLocaleString("en-CA", { timeZone: "America/Toronto", dateStyle: "medium", timeStyle: "short" }); }
