"use client";

import type { ReachedArtifact } from "../../domain/drift";

export type DriftProjection = { id: string; riskKind: string; status: string; currentValue?: string; proposedValue?: string; provenance?: string; paths?: readonly string[]; artifacts?: readonly ReachedArtifact[]; impactDigest: string; candidate?: Omit<ReplacementCandidateCommand, "operationKey"> };
export type ReplacementProjection = { id: string; revision: number; status: string; currentConfigurationId: string; candidateConfigurationId: string; impactDigest: string; proposedVersionId: string; immutable: true };
export type ReplacementCandidateCommand = { currentVersionId: string; proposedVersionId: string; ownerType: "product" | "profile"; ownerId: string; kind: "product_discovery" | "profile_effective"; expectedOwnerRevision: number; operationKey: string };
export type ReplacementActivationCommand = { candidateId: string; impactDigest: string; expectedOwnerRevision: number; expectedCandidateRevision: number; operationKey: string };

export function DriftReplacementsView({ drift, candidates, operationKey, onCreateCandidate, onActivateReplacement, issue }: { drift: readonly DriftProjection[]; candidates: readonly ReplacementProjection[]; operationKey: string; onCreateCandidate(command: ReplacementCandidateCommand): void; onActivateReplacement(command: ReplacementActivationCommand): void; issue?: string | null }) {
  if (issue) return <section className="error-state" role="alert">Drift authority is unknown: {issue}. Candidate and activation controls are hidden until the current version can be checked.</section>;
  const unresolved = drift.filter((item) => item.status !== "resolved"); const resolved = drift.filter((item) => item.status === "resolved");
  return <section><section className="panel"><h2>Drift &amp; Replacements</h2><p>Unresolved drift appears first. A candidate is not active; activation is a separate exact-digest decision.</p></section>{unresolved.map((item) => <DriftCard key={item.id} item={item} operationKey={operationKey} onCreateCandidate={onCreateCandidate} />)}{!unresolved.length && <section className="panel"><p>No unresolved drift is recorded.</p></section>}<section aria-label="Replacement candidates">{candidates.map((candidate) => <CandidateCard key={candidate.id} candidate={candidate} operationKey={operationKey} onActivateReplacement={onActivateReplacement} />)}</section><details><summary>Resolved drift and activation history ({resolved.length})</summary>{resolved.map((item) => <DriftCard key={item.id} item={item} operationKey={operationKey} onCreateCandidate={onCreateCandidate} />)}</details></section>;
}
function DriftCard({ item, operationKey, onCreateCandidate }: { item: DriftProjection; operationKey: string; onCreateCandidate(command: ReplacementCandidateCommand): void }) { const highRisk = ["capability", "proof_point", "claim_guardrail", "offer", "suppression"].includes(item.riskKind); const artifacts = item.artifacts ?? []; const containment = highRisk && artifacts.some((artifact) => artifact.status !== "not_present") ? "Affected outbound paused" : highRisk ? "Operational effects remain disabled in this pilot" : "No operational effect"; return <article className="panel"><span className="fit-pill">{highRisk ? "High-risk drift" : "Standard drift"} · {item.riskKind}</span><h2>Drift {item.id}</h2><dl className="confirmation-proof"><div><dt>Current / proposed</dt><dd>{item.currentValue ?? "not recorded"} / {item.proposedValue ?? "not recorded"}</dd></div><div><dt>Source / provenance</dt><dd>{item.provenance ?? "not recorded"}</dd></div><div><dt>Dependency path</dt><dd>{item.paths?.join(" -> ") ?? "source -> knowledge version -> typed configuration -> affected artifact"}</dd></div><div><dt>Containment</dt><dd>{containment}</dd></div></dl><h3>Impact preview</h3><ul>{(["Future schedules", "In-flight history", "Requalification", "Invalidation", "Reactivation", "Contacted/exported history"] as const).map((category) => <li key={category}>{category}: {artifacts.length ? "Affected" : "Not present"}</li>)}</ul><p>Reached artifacts: {artifacts.length}. Exact impact digest: {item.impactDigest}</p><button className="primary" type="button" disabled={!item.candidate} onClick={() => item.candidate && onCreateCandidate({ ...item.candidate, operationKey })}>Create replacement candidate</button>{!item.candidate && <p className="saved">Available after the server returns the exact candidate scope, versions, and expected revision.</p>}<p className="saved">Accept, Reject, Correct, and Rescope remain proposal-review decisions; candidate creation cannot activate a configuration or perform an operational effect.</p></article>; }
function CandidateCard({ candidate, operationKey, onActivateReplacement }: { candidate: ReplacementProjection; operationKey: string; onActivateReplacement(command: ReplacementActivationCommand): void }) { const active = candidate.status === "active"; return <article className="panel"><span className="fit-pill">{active ? "Replacement active" : "Candidate — not active"}</span><h2>Replacement candidate</h2><dl className="confirmation-proof"><div><dt>Candidate configuration</dt><dd>{candidate.candidateConfigurationId}</dd></div><div><dt>Current configuration</dt><dd>{candidate.currentConfigurationId}</dd></div><div><dt>Exact impact digest</dt><dd>{candidate.impactDigest}</dd></div></dl>{!active && <><p>Activation is a separate action against this exact preview and revisions. It records future-phase directives only; all operational controls remain disabled.</p><button className="primary" type="button" onClick={() => onActivateReplacement({ candidateId: candidate.id, impactDigest: candidate.impactDigest, expectedOwnerRevision: 1, expectedCandidateRevision: candidate.revision, operationKey })}>Activate replacement</button></>}</article>; }
