"use client";

import { useState } from "react";

export type KnowledgeItemProjection = { id: string; type: "knowledge_proposal" | "knowledge_version"; revision?: number; status?: string; origin?: string; kind: string; digest: string; destination: { scopeType: string; id: string }; value: { excerpt?: string }; provenance?: { reference?: string; custody?: string; retrievedAt?: number; privacy?: string; license?: { use?: string }; reuseEligibility?: string }; successorLineage?: { decision?: string }; immutable: true; quarantine?: { status: string } };
export type KnowledgeIntakeCommand = { action: "propose_repository_research" | "import_plain_text" | "propose_reuse" | "propose_allowlisted_package"; destination: { scopeType: string; locator: string }; kind: string; text: string; source: { reference: string; custody: string; retrievedAt: number }; privacy: "public" | "private" | "restricted"; license: { use: string }; reuseEligibility: string; operationKey: string };
export type KnowledgeReviewCommand = { proposalId: string; expectedRevision: number; decision: "accept" | "reject" | "correct" | "rescope"; correction?: string; destination?: { scopeType: string; locator: string }; operationKey: string };

export function KnowledgeLibraryView({ items, operationKey, onIntake, onReviewProposal, onProposeChange, issue }: { items: readonly KnowledgeItemProjection[]; operationKey: string; onIntake(command: KnowledgeIntakeCommand): void; onReviewProposal(command: KnowledgeReviewCommand): void; onProposeChange(item: KnowledgeItemProjection): void; issue?: string | null }) {
  const proposed = items.filter((item) => item.type === "knowledge_proposal"); const confirmed = items.filter((item) => item.type === "knowledge_version"); const [tab, setTab] = useState<"proposed" | "confirmed">(proposed.length ? "proposed" : "confirmed");
  if (issue) return <section className="error-state" role="alert">Knowledge authority is unknown: {issue}. Mutation controls are hidden until you check the current version.</section>;
  const visible = tab === "proposed" ? proposed : confirmed;
  return <section className="knowledge-library-view"><div className="panel"><h2>Knowledge Library</h2><p>Every card names its destination; proposed content has no authority until an owner promotion decision.</p><div aria-label="Knowledge status"><button type="button" aria-current={tab === "proposed" ? "page" : undefined} onClick={() => setTab("proposed")}>Proposed ({proposed.length})</button><button type="button" aria-current={tab === "confirmed" ? "page" : undefined} onClick={() => setTab("confirmed")}>Confirmed ({confirmed.length})</button></div></div>{tab === "proposed" && <IntakePanels operationKey={operationKey} onIntake={onIntake} />}{!visible.length ? <section className="panel"><h3>No {tab} Knowledge</h3><p>{tab === "proposed" ? "No reviewable proposed knowledge matches this scope." : "No confirmed Knowledge Version matches this scope."}</p></section> : visible.map((item) => <KnowledgeCard key={item.id} item={item} operationKey={operationKey} onReviewProposal={onReviewProposal} onProposeChange={onProposeChange} />)}</section>;
}

function IntakePanels({ operationKey, onIntake }: { operationKey: string; onIntake(command: KnowledgeIntakeCommand): void }) {
  const [kind, setKind] = useState("evidence"); const [text, setText] = useState(""); const [source, setSource] = useState(""); const submit = (action: KnowledgeIntakeCommand["action"], custody: string, eligibility: string) => { if (text.trim() && source.trim()) onIntake({ action, destination: { scopeType: "company", locator: "Digitalrain" }, kind, text, source: { reference: source, custody, retrievedAt: Date.now() }, privacy: "public", license: { use: "owner review" }, reuseEligibility: eligibility, operationKey }); };
  return <section className="panel"><h2>Safe intake</h2><p>Each action creates Proposed Knowledge only. The application records source metadata; it does not fetch URLs.</p><label>Knowledge kind <input value={kind} onChange={(event) => setKind(event.target.value)} /></label><label>Plain-text excerpt <textarea maxLength={6000} value={text} onChange={(event) => setText(event.target.value)} /></label><label>Source reference or immutable reuse reference <input value={source} onChange={(event) => setSource(event.target.value)} /></label><div><button type="button" onClick={() => submit("propose_repository_research", "public / owner-authorized", "repository_research")}>Record repository research as Proposed Knowledge</button><button type="button" onClick={() => submit("import_plain_text", "owner-provided UTF-8 text", "plain_text_only")}>Import plain text as Proposed Knowledge</button><button type="button" onClick={() => submit("propose_reuse", "same-Company / same-Product confirmed", "company_only")}>Reuse confirmed knowledge as Proposed Knowledge</button><button type="button" onClick={() => submit("propose_allowlisted_package", "allowlisted package", "allowlisted_package")}>Reuse allowlisted package as Proposed Knowledge</button></div><p className="saved">Plain UTF-8 text only, maximum 6,000 characters. No file picker, drag-and-drop, multipart upload, parser, scanner, quarantine release, filename/path authority, or operational import is available. Contacts, prospects, outreach, suppression, secrets, and unapproved private sources cannot be promoted.</p></section>;
}

function KnowledgeCard({ item, operationKey, onReviewProposal, onProposeChange }: { item: KnowledgeItemProjection; operationKey: string; onReviewProposal(command: KnowledgeReviewCommand): void; onProposeChange(item: KnowledgeItemProjection): void }) {
  const [decision, setDecision] = useState<KnowledgeReviewCommand["decision"]>("accept"); const [correction, setCorrection] = useState(""); const isProposal = item.type === "knowledge_proposal";
  return <article className="panel"><span className={isProposal ? "fit-pill" : "status-badge proven"}>{isProposal ? "Proposed Knowledge" : "Confirmed Knowledge"}</span><h2>{item.kind}</h2><p>{item.value.excerpt ?? "No plain-text excerpt is present."}</p><dl className="confirmation-proof"><div><dt>Destination</dt><dd>{item.destination.scopeType} / {item.destination.id}</dd></div><div><dt>Immutable reference</dt><dd>{item.id}</dd></div><div><dt>Digest</dt><dd>{item.digest}</dd></div><div><dt>Origin / custody</dt><dd>{item.origin ?? "confirmed lineage"} / {item.provenance?.custody ?? "not recorded"}</dd></div><div><dt>Provenance / privacy / license</dt><dd>{item.provenance?.reference ?? "not recorded"} / {item.provenance?.privacy ?? "not recorded"} / {item.provenance?.license?.use ?? "not recorded"}</dd></div><div><dt>Reuse / decision lineage</dt><dd>{item.provenance?.reuseEligibility ?? "not recorded"} / {item.successorLineage?.decision ?? "not recorded"}</dd></div></dl>{item.quarantine && <p role="alert">Unscanned uploaded content is not renderable or promotable.</p>}{isProposal ? <><p className="saved">Proposed Knowledge has no authority until you promote it.</p><fieldset><legend>Review proposal against this exact snapshot</legend>{(["accept", "reject", "correct", "rescope"] as const).map((choice) => <label key={choice}><input type="radio" name={`proposal-${item.id}`} checked={decision === choice} onChange={() => setDecision(choice)} />{choice}</label>)}{(decision === "correct" || decision === "rescope") && <label>{decision === "correct" ? "Corrected plain text" : "Confirmed destination"}<input required value={correction} onChange={(event) => setCorrection(event.target.value)} /></label>}</fieldset><button className="primary" type="button" onClick={() => onReviewProposal({ proposalId: item.id, expectedRevision: item.revision ?? 1, decision, ...(decision === "correct" ? { correction } : {}), ...(decision === "rescope" ? { destination: { scopeType: item.destination.scopeType, locator: correction } } : {}), operationKey })}>{decision === "correct" ? "Record correction" : decision === "rescope" ? "Record rescope" : decision === "accept" ? "Accept" : "Reject"}</button></> : <><p className="saved">Confirmed Knowledge is read-only. Version, decision, Toronto confirmation time, audit references, supersedes, and dependencies are immutable server lineage.</p><button type="button" className="outline" onClick={() => onProposeChange(item)}>Propose change</button></>}</article>;
}
